(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e2=function(a){a.R("cardstatechange",g.bX(a)&&g.cX(a)?1:0)},cBa=function(a){var b=g.ug(a);
a=g.Bg(a);return new g.eg(b.x,b.y,a.width,a.height)},dBa=function(a){return Math.pow(a,3)},eBa=function(a){return 3*a*a-2*a*a*a},h2=function(a){a=g.Ta(a);
delete f2[a];g.Vb(f2)&&g2&&g2.stop()},gBa=function(){g2||(g2=new g.G(function(){fBa()},20));
var a=g2;a.isActive()||a.start()},fBa=function(){var a=g.z();
g.Ib(f2,function(b){hBa(b,a)});
g.Vb(f2)||gBa()},i2=function(a,b,c,d){g.An.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.o=a;this.H=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.F=0;this.B=null},hBa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;iBa(a,a.progress);1==a.progress?(a.va=0,h2(a),a.Xe(),a.Mo()):a.ub()&&a.zv()},iBa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.o.length);for(var c=0;c<a.o.length;c++)a.coords[c]=(a.H[c]-a.o[c])*b+a.o[c]},jBa=function(a,b){g.Jl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.va},j2=function(a,b,c,d,e){i2.call(this,b,c,d,e);
this.element=a},k2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
j2.call(this,a,b,c,d,e)},l2=function(a){g.B.call(this);
this.u=a||window;this.o=[]},m2=function(a){return a.baseUrl||null},n2=function(a,b){return g.Ie(g.Oc(a,b,void 0),function(c){return!!c})},kBa=function(a,b,c){function d(xb){var Wa=xb.hovercardButton;
if(!Wa)return null;Wa=Wa.subscribeButtonRenderer;if(!Wa)return null;var fb=f(Wa.unsubscribedButtonText),ge=f(Wa.subscribedButtonText);if(Wa.subscribed){var wi=f(Wa.subscriberCountWithUnsubscribeText);var xi=f(Wa.subscriberCountText)}else wi=f(Wa.subscriberCountText),xi=f(Wa.subscriberCountWithSubscribeText);var zg=null;return xb.signinEndpoint&&(zg=g.Qb(xb,"signinEndpoint","webNavigationEndpointData","url"),!zg)?null:fb&&(ge||zg)?{subscribed:Wa.subscribed,subscribeText:fb,subscribeCount:wi,unsubscribeText:ge,
unsubscribeCount:xi,enabled:Wa.enabled,signinUrl:zg,classic:xb.useClassicSubscribeButton}:null}
function e(xb){if(xb){var Wa=[],fb=xb.videoId;fb&&Wa.push("v="+fb);(fb=xb.playlistId)&&Wa.push("list="+fb);(xb=xb.startTimeSeconds)&&Wa.push("t="+xb);return"/watch?"+Wa.join("&")}}
function f(xb){if(!xb)return null;var Wa=xb.simpleText;return Wa?Wa:xb.runs?g.Oc(xb.runs,function(fb){return fb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,A=null,D=null,E=null,H=null,T=null;if("VIDEO"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"==h){if(x=g.Qb(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?A=d(b):D=f(b.subscribersText)}else"WEBSITE"==
h?((E=g.Qb(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(T=f(b.additionalFeesText)),(n=g.Qb(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.Qb(b,"title","accessibility","accessibilityData","label");var P=b.endpoint?b.endpoint.clickTrackingParams:null,Qa="";if(b.metadata){var kb=f(b.metadata);kb&&(Qa=kb)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Qa,callToAction:f(b.callToAction),
aA:b.image,iconUrl:E,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:A,subscribersText:D,isSubscribe:x,targetUrl:m,BI:n,Yc:{itct:P},LP:p,ln:a?a:null,FI:b.isPlaceholder,impressionUrls:n2(b.impressionUrls||[],m2),uI:n2(b.hovercardShowUrls||[],m2),clickUrls:n2(l.loggingUrls||[],m2),visualElement:g.Hs(b.trackingParams),productPrice:H,
additionalFeesText:T}},o2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=n2(a.impressionUrls||[],m2);a.trackingParams&&(c.visualElement=g.Hs(a.trackingParams));c.elements=n2(a.elements||[],function(d,e){return kBa(b,d,e)});
return c},p2=function(a){g.FS.call(this,a);
this.B=this.u=null;this.o={};this.H={};this.F=this.A=null;this.M=[];a=a.N();this.P=g.bC(a)||g.dC(a);this.S=!0;this.J=0;this.C=new g.ns(this);g.C(this,this.C);this.C.K(this.player,g.ED("creatorendscreen"),this.UI);this.C.K(this.player,g.FD("creatorendscreen"),this.VI);this.C.K(this.player,"resize",this.ZB);this.C.K(window,"focus",this.GO);this.load();var b=g.De("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.$f(this,function(){g.He(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},lBa=function(a){return a.player.getVideoData().Dc?"current":a.P?"new":"current"},q2=function(a){return"creator-endscreen-editor"===a.player.N().playerStyle},r2=function(a,b,c){c=void 0===c?!0:c;
g.hX(a.player,"creatorendscreen");a.A&&(a.A.dispose(),a.A=null,a.F.dispose(),a.F=null);for(var d in a.o)a.o[d].dispose();a.o={};a.H={};0<a.M.length&&(a.M.forEach(function(l){l.dispose()}),a.M.length=0);
a.J=0;if((a.u=b)&&b.elements){c&&mBa(a);c=[];d=new g.BD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.N().o||(a.A=new g.V({D:"div",I:"ytp-ce-shadow"}),g.OO(a.player,a.A.element,4),a.F=new g.yN(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=nBa(a,e);a.o[e.id]=f;a.H[e.id]=e;g.OO(a.player,f.element,4);var h=new g.BD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);oBa(a,f,e)}g.nM(a.player,c);
a.ZB()}},mBa=function(a){var b=g.Ls(),c=g.Ns();
c&&b&&a.u.visualElement&&g.ht(c,b,a.u.visualElement)},nBa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",da:["ytp-ce-element","ytp-ce-video"],O:{tabindex:"0","aria-label":b.ln||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",O:s2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",O:{href:t2(a,b.targetUrl),tabindex:"-1"},L:[{D:"div",da:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Gn(b.title||"")},T:b.title},{D:"div",I:"ytp-ce-video-duration",T:b.videoDuration}]}]};
c=new g.V(c);break;case "PLAYLIST":c={D:"div",da:["ytp-ce-element","ytp-ce-playlist"],O:{tabindex:"0","aria-label":b.ln||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",O:s2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",O:{href:t2(a,b.targetUrl),tabindex:"-1"},L:[{D:"div",da:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Gn(b.title||"")},T:b.title},{D:"div",I:"ytp-ce-playlist-count",L:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",T:b.playlistLength}]}]}]};c=new g.V(c);break;case "CHANNEL":c={D:"div",da:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],O:{tabindex:"0","aria-label":b.ln||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",L:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
L:[{D:"div",I:"ytp-ce-expanding-overlay-body",L:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{D:"a",da:["ytp-ce-channel-title","ytp-ce-link"],O:{href:t2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Gn(b.title||"")},T:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",L:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",T:b.subscribersText}:"",b.metadata?{D:"div",da:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],T:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:s2(b)}]};c=new g.V(c);var d=g.pe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.N().o){var e=null;var f=b.Yc.itct}else e="endscreen",f=null;e=new g.lY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.M.push(e)}break;case "WEBSITE":c={D:"div",da:["ytp-ce-element","ytp-ce-website"],O:{tabindex:"0","aria-label":b.ln||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",L:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",L:[{D:"div",I:"ytp-ce-expanding-overlay-body",
L:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{D:"div",I:"ytp-ce-website-title",O:{dir:g.Gn(b.title||"")},T:b.title},{D:"div",I:"ytp-ce-website-metadata",T:b.metadata},{D:"a",da:["ytp-ce-website-goto","ytp-ce-link"],O:{href:t2(a,b.targetUrl),target:"_blank",tabindex:"-1"},T:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:s2(b)},{D:"div",I:"ytp-ce-expanding-icon",O:pBa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
L:[{D:"div",I:"ytp-ce-merchandise-price",T:b.productPrice}]},b.additionalFeesText&&c.L.push({D:"div",I:"ytp-ce-merchandise-additional-fees",T:b.additionalFeesText})),c={D:"div",da:["ytp-ce-element","ytp-ce-merchandise"],O:{tabindex:"0","aria-label":b.ln||"","aria-hidden":"true"},L:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",L:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
L:[{D:"div",I:"ytp-ce-expanding-overlay-body",L:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{D:"div",I:"ytp-ce-merchandise-title",O:{dir:g.Gn(b.title||"")},T:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",T:b.metadata},{D:"a",da:["ytp-ce-merchandise-goto","ytp-ce-link"],O:{href:t2(a,b.targetUrl),target:"_blank",tabindex:"-1"},T:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",O:s2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",L:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
T:b.callToAction}]}]},c=new g.V(c)}b.FI&&g.I(c.element,"ytp-ce-placeholder");return c},s2=function(a){if(a.aA)var b=a.aA.thumbnails;
return pBa(b?b[b.length-1].url:null)},pBa=function(a){return a?{style:"background-image: url("+a+")"}:{}},oBa=function(a,b,c){function d(){h(1)}
function e(){h(-1)}
b.ia("mouseenter",(0,g.y)(a.Tw,a,b,c));b.ia("mouseleave",(0,g.y)(a.Uw,a,b,c));a.player.N().o||b.ia("click",(0,g.y)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.ia("click",(0,g.y)(a.gD,a,c));b.ia("keypress",(0,g.y)(a.gD,a,c));b.ia("focus",(0,g.y)(function(l,m){this.Tw(l,m)},a,b,c));
b.ia("blur",(0,g.y)(function(l,m){this.Uw(l,m)},a,b,c));
b.ia("touchstart",(0,g.y)(a.Tw,a,b,c));var f=g.re("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.yn(b.element,"ytp-ce-element-hover");g.yn(b.element,"ytp-ce-force-expand")});
b.ia("keydown",(0,g.y)(function(l,m){this.S=9==m.keyCode&&!m.shiftKey},a,b));
var h=(0,g.y)(function(l,m,n){this.J+=n;0<this.J?(g.I(l.element,"ytp-ce-force-expand"),u2(this,m.id,!0)):(g.yn(l.element,"ytp-ce-force-expand"),g.yn(l.element,"ytp-ce-element-hover"),u2(this,m.id,!1))},a,b,c);
c=(0,g.y)(function(l,m){m&&(l.ia("blur",g.Ua(function(){"none"!=m.style.display&&a.S&&m.focus()})),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
c(g.re("ytp-sb-subscribe",b.element));c(g.re("ytp-sb-unsubscribe",b.element));b.ia("focus",d);b.ia("blur",e)},t2=function(a,b){var c=a.player.N();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.GC(c)+b}else return"";return b},u2=function(a,b,c){a.A&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},v2=function(a,b,c){function d(){f||(e++,e==b.length&&(h.stop(),c&&c()))}
if(!b||0==b.length||q2(a))c&&c();else{b=qBa(a,b);var e=0,f=!1,h=new g.G(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.tt(b[a],d)}},w2=function(a,b,c){v2(a,b.clickUrls,c);
(a=g.Ns())&&b.BI&&g.kt(a,b.visualElement)},qBa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(rBa(b[e],c));return d},rBa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},sBa=function(a){return Array.isArray(a)&&a.length?a[0]:a},x2=function(a){return"string"===typeof a?a:""},y2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},tBa=function(a){this.externalId=a},uBa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},z2=function(a){return a.value?a.value:null},A2=function(a){if(!a)return null;
var b=g.Jc(x2(a.value));b=g.Fc(b);if(!b)return null;var c=y2(a.target,vBa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new uBa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},wBa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},zBa=function(a){if(!a)return null;
var b=y2(a.type,xBa),c=y2(a.trigger,yBa),d=sBa(a.url);d=A2(d?d:null);a=sBa(a.subscribeData);var e=a?a:null;e?(a=x2(e.external_user_id),e=x2(e.subscription_token),a=a&&e?new tBa(a):null):a=null;return b?new wBa(b,c,d,a):null},B2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ABa=function(a,b){return g.gb(a.action,b,void 0)},BBa=function(a,b){this.context=a;
this.o=b},D2=function(a){return a.customMessage?C2("div","iv-card-message",a.customMessage):""},E2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",O:{style:c},L:d}},F2=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(C2("li","",c.value));return{D:"ul",I:"iv-card-meta-info",L:b}},C2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Gn(c);return{D:a,O:b,T:c}},CBa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jq&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jq+");");c.dir=g.Gn(a.customMessage);var d=[{D:"span",T:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",da:b,O:c,L:d}},G2=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.o(e.value,d,c.id,c.Yc,c.Pe.click,5)}},DBa=function(a,b){this.merchant=a;
this.price=b},EBa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},FBa=function(a,b){return b?b:EBa(a)?"current":"new"},H2=function(a,b){g.B.call(this);
var c=this;this.element=a;this.context=b;this.Ca=!1;this.na=new Map;this.oa=new Map;this.context.G.addEventListener(g.ED("annotations_module"),function(d){(d=c.na.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.FD("annotations_module"),function(d){(d=c.oa.get(d))&&d.apply(c)})},I2=function(a,b,c,d,e,f,h){a.context.o.ia(b,"click",function(){a.ww(c,d,e,f||[],h||0)});
a.context.o.ia(b,"touchstart",function(){a.Ca=!1});
a.context.o.ia(b,"touchmove",function(){a.Ca=!0})},GBa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},J2=function(a,b,c){return{gB:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
fF:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
qt:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},M2=function(a,b,c){H2.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.aa=this.bb=this.A=this.gd=!1;this.ca=null;this.cards=[];this.Ga=this.J=this.X=this.C=this.fa=this.o=null;this.P=[];this.H=this.Vc=this.W=null;this.F=0;this.U=new g.G(g.Ma,c.B.Oc?4E3:3E3);g.C(this,this.U);this.xa=new g.G(g.Ma);g.C(this,this.xa);this.S=new BBa(c,function(e,f,h,l,m,n){I2(d,e,f,h,l,m,n)});
this.M=new g.V({D:"div",I:"iv-drawer",O:{id:"iv-drawer"},L:[{D:"div",I:"iv-drawer-header",O:{"aria-role":"heading"},L:[{D:"span",I:"iv-drawer-header-text"},{D:"button",da:["iv-drawer-close-button","ytp-button"],O:{"aria-label":"Infokarten ausblenden",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});g.C(this,this.M);this.B=this.M.element;this.ra=new g.yN(this.M,330);g.C(this,this.ra);this.Ja=g.re("iv-drawer-header-text",this.B);this.u=g.re("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.bb&&K2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.bb=d.A)&&L2(d)})},HBa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){K2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){L2(a)});
var d=c.headerText;g.Le(a.Ja,d);a.J&&a.J.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.W=g.Hs(c.trackingParams);a.H=g.Hs(c.closeTrackingParams);a.Vc=g.Hs(c.iconTrackingParams)},IBa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.F;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"simple",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Yc:N2(a,c,b,d),sponsored:!1,Pe:J2(d,e,d.command),Xh:d.trackingParams?g.Hs(d.trackingParams):null,cg:e.trackingParams?g.Hs(e.trackingParams):
null,Vc:f&&f.trackingParams?g.Hs(f.trackingParams):null,imageUrl:O2(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.U(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,jq:null,title:d.title?g.U(d.title):"",customMessage:d.callToAction?g.U(d.callToAction):"",url:d.command.urlEndpoint.url?A2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};P2(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"collaborator",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Yc:N2(a,c,b,d),sponsored:!1,Pe:J2(d,e,d.endpoint),Xh:d.trackingParams?g.Hs(d.trackingParams):null,cg:e.trackingParams?g.Hs(e.trackingParams):null,Vc:f&&f.trackingParams?g.Hs(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.U(d.customText):null,hE:O2(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.U(d.channelName):"",metaInfo:[d.subscriberCountText?g.U(d.subscriberCountText):""],url:A2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};P2(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"playlist",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Yc:N2(a,c,b,d),sponsored:!1,Pe:J2(d,e,d.action),Xh:d.trackingParams?g.Hs(d.trackingParams):null,cg:e.trackingParams?g.Hs(e.trackingParams):null,Vc:f&&f.trackingParams?g.Hs(f.trackingParams):
null,yp:O2(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.U(d.customMessage):null,playlistVideoCount:g.U(d.playlistVideoCount),title:d.playlistTitle?g.U(d.playlistTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.videoCountText?g.U(d.videoCountText):""],url:A2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:GBa(d.action)})};P2(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"video",teaserText:g.U(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Yc:N2(a,c,b,d),sponsored:!1,Pe:J2(d,e,d.action),Xh:d.trackingParams?g.Hs(d.trackingParams):null,cg:e.trackingParams?g.Hs(e.trackingParams):null,Vc:f&&f.trackingParams?g.Hs(f.trackingParams):null,yp:O2(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.U(d.lengthString):null,customMessage:d.customMessage?g.U(d.customMessage):null,title:d.videoTitle?g.U(d.videoTitle):"",metaInfo:[d.channelName?g.U(d.channelName):"",d.viewCountText?g.U(d.viewCountText):""],isLiveNow:!!d.badge,url:A2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:GBa(d.action)})};P2(a,c)}a.F++},O2=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},N2=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},KBa=function(a,b){var c=JBa(a,b);
c&&(c===a.o&&(a.o=null),a.G.removeCueRange(c.card.id),g.He(c.Au),g.qb(a.cards,c),a.lq(),Q2(a))},K2=function(a,b,c){if(!a.A){a.ra.show();
a.fa=new g.G(function(){g.I(a.context.G.getRootNode(),g.d0.IV_DRAWER_OPEN)},0);
a.fa.start();a.ca=g.ap(a.u,"mousewheel",function(h){a.U.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.A=!0;var d=g.Ns();d&&a.W&&a.H&&g.it(d,[a.W,a.H]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.JB||(f.JB=!0,LBa(a.context.logger,f.card.Pe.gB,b)),d&&g.it(d,[f.card.Xh]);e2(a.G);c&&(a.C=new g.G(function(){a.X=a.J;a.Ga.focus()},330),a.C.start())}},L2=function(a){a.A&&(a.ra.hide(),g.bp(a.ca),a.ca=null,g.yn(a.context.G.getRootNode(),g.d0.IV_DRAWER_OPEN),a.A=!1,e2(a.G),a.C&&a.C.stop(),a.C=new g.G(function(){a.X&&(a.X.focus(),a.X=null)},330),a.C.start())},NBa=function(a){g.xn(a.Ea(),
[g.d0.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.OO(a.G,a.B,5);MBa(a);a.J=g.re("ytp-cards-button",a.G.getRootNode());a.Ga=g.re("iv-drawer-close-button",a.B);a.gd=!0},MBa=function(a){var b=g.re("iv-drawer-close-button",a.B);
a.context.o.ia(b,"click",a.VG,a);a.context.o.ia(a.u,"touchend",function(){a.U.start()});
a.context.o.ia(a.u,"scroll",a.jH,a);a.context.u.subscribe("onHideControls",function(){a.aa=!0});
a.context.u.subscribe("onShowControls",function(){a.aa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.aa=g.wn(a.G.getRootNode(),"ytp-autohide")});
a.P.push(g.Lo("iv-button-shown",a.JI,a));a.P.push(g.Lo("iv-button-hidden",a.II,a));a.P.push(g.Lo("iv-teaser-shown",a.GJ,a));a.P.push(g.Lo("iv-teaser-hidden",a.KI,a));a.P.push(g.Lo("iv-teaser-clicked",a.FJ,a))},P2=function(a,b){a.gd||NBa(a);
KBa(a,b.id);var c=OBa(a,b);if(c){var d={card:b,Au:c.element,JB:!1},e=PBa(a,d);g.wb(a.cards,e,0,d);c.Y(a.u,e);a.lq();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.A||(a.o=d,Q2(a),QBa(a,d),K2(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&RBa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){RBa(a,d)}),Q2(a))}},OBa=function(a,b){switch(b.type){case "simple":var c=a.S;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",T:b.displayDomain}:void 0;var e=CBa(b);d={D:"div",da:["iv-card"],L:[{D:"a",I:"iv-click-target",O:{href:b.url?z2(b.url)||"":""},L:[E2(b.imageUrl,d),{D:"div",I:"iv-card-content",L:[C2("h2",void 0,b.title),e]}]}]};d=new g.V(d);G2(c,g.qe("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.S,d={D:"div",da:["iv-card","iv-card-channel"],L:[{D:"a",da:["iv-click-target"],O:{href:z2(b.url)||"","data-ytid":b.channelId},L:[E2(b.hE),
{D:"div",I:"iv-card-content",L:[D2(b),{D:"h2",I:"iv-card-primary-link",T:b.title},F2(b)]}]}]},d=new g.V(d),G2(c,g.qe("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.S,d={D:"div",da:["iv-card","iv-card-playlist"],L:[{D:"a",I:"iv-click-target",O:{href:z2(b.url)||""},L:[E2(b.yp,{D:"div",I:"iv-card-image-overlay",L:[{D:"span",I:"iv-card-playlist-video-count",T:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",L:[D2(b),C2("h2","iv-card-primary-link",b.title),F2(b)]}]}]},d=new g.V(d),
G2(c,g.qe("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.S;var f=!g.nb(b.offers);d=["iv-card"];e="";var h=CBa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",I:"iv-card-offer-price",T:h.price}),h.merchant&&f.push({D:"div",I:"iv-card-offer-merchant",T:h.merchant}),h={D:"div",L:f});f=b.url?z2(b.url)||"":"";d={D:"div",da:d,O:{tabindex:"0"},L:[{D:"a",da:["iv-card-image","iv-click-target"],O:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",L:[b.sponsored?{D:"div",I:"iv-card-sponsored",L:["Anzeige",{D:"div",I:"iv-ad-info-container",L:[{D:"div",I:"iv-ad-info",T:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",L:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",O:{href:f},L:[C2("h2",e,b.title),h]}]}]};d=new g.V(d);e=g.De("span");g.Le(e,"Du siehst dieses Produkt, weil wir glauben, dass es f\u00fcr das Video relevant ist. Google erh\u00e4lt daf\u00fcr m\u00f6glicherweise eine Entlohnung vom H\u00e4ndler.");
d.Yb(e,"adInfo");G2(c,g.qe("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.S,d=b.isLiveNow?{D:"span",da:["yt-badge","yt-badge-live"],T:"JETZT LIVE"}:null,d={D:"div",da:["iv-card","iv-card-video"],L:[{D:"a",I:"iv-click-target",O:{href:z2(b.url)||""},L:[E2(b.yp,b.videoDuration?{D:"span",I:"iv-card-video-duration",T:b.videoDuration}:void 0),{D:"div",I:"iv-card-content",L:[D2(b),C2("h2","iv-card-primary-link",b.title),F2(b),d]}]}]},d=new g.V(d),G2(c,g.qe("iv-click-target",d.element),
b,b.url),d;default:return null}},PBa=function(a,b){if(0===a.cards.length)return 0;
var c=g.ib(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},SBa=function(a){return a.o?"productListing"===a.o.card.type:g.gh(a.cards,function(b){return"productListing"===b.card.type})},Q2=function(a){g.J(a.G.getRootNode(),"ytp-cards-shopping-active",SBa(a))},RBa=function(a,b){if(!g.wn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.o!==b){var c=g.Ns(),d=a.o?a.o.card.Vc:a.Vc;
c&&d&&g.jt(c,[d]);a.o=b;Q2(a)}if(c="none"!=a.Ea().style.display)2===a.context.G.getPresentingPlayerType()?c=1===a.context.G.getAdState():(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.aX(g.SW(a.G)))&&d.pw(!0,c));a.xa.isActive()||((!a.A||!a.U.isActive()&&a.aa)&&QBa(a,b),a.xa.start(910+b.card.teaserDurationMs))}},QBa=function(a,b){if(a.M.Pa){var c=new i2([0,
a.u.scrollTop],[0,b.Au.offsetTop],600,eBa);a.context.A.ia(c,"animate",function(d){a.u.scrollTop=d.y});
a.context.A.ia(c,"finish",function(d){a.u.scrollTop=d.y});
c.play()}else g.FM(a.M,!0),a.u.scrollTop=b.Au.offsetTop,g.FM(a.M,!1)},R2=function(a){return a.o&&a.o.card?a.o.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},JBa=function(a,b){return g.gb(a.cards,function(c){return c.card.id===b})},S2=function(a,b,c){H2.call(this,a,b);
this.annotation=c;this.isActive=!1},TBa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},T2=function(a,b,c){S2.call(this,a,b,c);
this.u=null;this.H=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},UBa=function(a,b){var c=void 0===c?0:c;
var d=cBa(b).width;g.sg(b,d);c=new k2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,dBa);g.C(a,c);a.context.A.ia(c,"begin",function(){g.Cg(b,!0)});
c.play()},XBa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
da:["iv-branding-context-name"],T:b.channel_name}),d=a.createElement({D:"div",da:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.o=new g.lY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.G),a.o.Y(d));var f=a.createElement({D:"div",da:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",da:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Cg(h,!1);var l=a.createElement({D:"div",da:["branding-context-container-outer"]});l.appendChild(h);g.F(l,"right",b.image_width+"px");a.Ea().appendChild(l);a.A=new g.G(function(){VBa(a,h,l)},500);
g.C(a,a.A);a.context.o.ia(a.Ea(),"mouseover",function(){WBa(a,h,l,f,b.image_height)});
a.context.o.ia(a.Ea(),"mouseout",function(){a.A.start()})}},WBa=function(a,b,c,d,e){a.A.stop();
if(!a.B){var f=g.Bg(b);a.o||(b.style.width=g.rg(f.width,!0),c.style.width=g.rg(f.width,!0));g.F(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.F(d,"right","1px");a.B=!0;g.Cg(b,!0);a.C=new g.G(function(){g.I(this.Ea(),"iv-branding-active")},0,a);
a.C.start()}},VBa=function(a,b,c){g.yn(a.Ea(),"iv-branding-active");
a.F=new g.G(function(){g.Cg(b,!1);a.o||(c.style.width=g.rg(0,!0))},250);
a.F.start();a.B=!1},YBa=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},U2=function(a,b,c){S2.call(this,a,b,c);
var d=this;this.J=this.isCollapsed=this.M=!1;this.F=5E3;this.u=this.A=this.o=this.B=null;this.H=this.createElement({D:"div",da:["iv-promo-contents"]});this.C=new g.G(function(){d.o.setAttribute("aria-hidden","true");g.Cg(d.A,!1);g.Cg(d.u,!0)},700,this);
g.C(this,this.C)},ZBa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.F=b.collapsedelay_ms||a.F;var d=["iv-promo","iv-promo-inactive"];a.Ea().setAttribute("aria-hidden","true");a.Ea().setAttribute("aria-label","Werbung");a.Ea().tabIndex=0;var e=a.annotation.Uc(),f=b.image_url;if(f){var h=a.createElement({D:"div",da:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",O:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({D:"span",I:"iv-promo-video-duration",T:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",I:"iv-promo-playlist-length",T:b.playlist_length.toString()}),h.appendChild(f));e&&I2(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",I:"iv-promo-txt"}),g.gd(f,z2(e)),a.o=f):a.o=a.createElement({D:"div",I:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",L:[{D:"strong",T:b.text_line_1}]});
var m=a.createElement({D:"p",L:[{D:"span",I:"iv-promo-link",T:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",da:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",da:["iv-button","iv-promo-button"],L:[{D:"span",I:"iv-button-content",T:f}]});var p=a.createElement({D:"div",I:"iv-promo-button-container"});p.appendChild(f);e&&I2(a,a.Ea(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");
e&&I2(a,a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",L:[{D:"span",T:b.text_line_1}]}),m=a.createElement({D:"p",L:[{D:"strong",T:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",da:["yt-badge","iv-promo-badge-live"],T:"JETZT LIVE"})),g.I(a.o,"iv-click-target"),e&&I2(a,a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);p&&a.H.appendChild(p);
c=a.createElement({D:"div",I:"iv-promo-actions"});a.u=a.createElement({D:"button",da:["iv-promo-expand","ytp-button"]});a.u.title="Maximieren";a.context.o.ia(a.u,"click",function(r){V2(a,5E3,r)});
c.appendChild(a.u);g.Cg(a.u,!1);a.context.o.ia(a.Ea(),"mouseover",a.cI,a);a.context.o.ia(a.Ea(),"mouseout",a.bI,a);a.context.o.ia(a.Ea(),"touchend",function(r){V2(a,5E3,r)});
a.A=a.createElement({D:"button",da:["iv-promo-close","ytp-button"]});a.A.title="Schlie\u00dfen";a.context.o.ia(a.A,"click","cta"===a.annotation.style&&b.text_line_3?a.VH:a.UH,a);c.appendChild(a.A);g.xn(a.Ea(),d);h&&(a.Ea().appendChild(h),n&&h.appendChild(n));a.Ea().appendChild(a.H);a.Ea().appendChild(c)},V2=function(a,b,c){c.stopPropagation();
$Ba(a);aCa(a,b);a.o.focus()},bCa=function(a){a.isCollapsed||a.J||a.B||(g.I(a.Ea(),"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},$Ba=function(a){a.C.stop();
a.isCollapsed&&(g.zn(a.Ea(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Cg(a.u,!1),g.Cg(a.A,!0))},aCa=function(a,b){a.B||(a.B=g.Rm(function(){W2(this);
bCa(this)},b,a))},W2=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},cCa=function(a){this.G=a},LBa=function(a,b,c){b&&(c?X2(a,b.map(function(d){return g.ln(d,c)})):X2(a,b))},X2=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.tt(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},Y2=function(a){g.FS.call(this,a);
var b=this;this.M=!1;this.loadNumber=0;this.H={};this.logger=new cCa(this.player);this.C=new g.ns(this);this.F=this.A=null;this.events=new g.ns(this);this.J=this.o=null;this.P=[];g.C(this,this.C);this.C.K(this.player,"onVideoAreaChange",function(){b.R("onVideoAreaChange")});
this.C.K(this.player,"onHideControls",function(){b.R("onHideControls")});
this.C.K(this.player,"onShowControls",function(){b.R("onShowControls")});
this.C.K(this.player,"resize",function(d){b.R("resize",d)});
this.C.K(this.player,"presentingplayerstatechange",function(d){b.R("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.EJ,this);this.subscribe("resize",this.Ds,this);this.player.N().M.subscribe("vast_info_card_add",this.QD,this);g.C(this,this.events);this.S=this.createElement({D:"div",I:"video-custom-annotations"});this.u=new g.V({D:"div",da:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.OO(this.player,this.u.element,4);this.u.hide();this.B=new g.V({D:"div",da:["ytp-iv-video-content"]});g.C(this,this.B);a=this.createElement({D:"div",I:"video-annotations"});
a.appendChild(this.S);this.B.element.appendChild(a);dCa(this)&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.$f(this,function(){g.He(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},eCa=function(a){a=a.createElement({D:"div",
da:["annotation","annotation-type-custom"]});g.Cg(a,!1);return a},dCa=function(a){var b=a.player.N();
a=a.player.getVideoData();return 1===(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.KF||b.M.get(a.videoId)||g.fG(a)||g.gG(a)?!0:!1},fCa=function(a,b){var c=!b.isCued()&&!g.S(b,1024);
g.FM(a.u,c);g.FM(a.B,c)},gCa=function(a,b,c){a.M=!0;
a.F=g.mq(b,c)},hCa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ra(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(hCa(a,e))}return c},kCa=function(a){var b=a.player.getVideoData();
if(b.Lf){var c=a.player.N().M.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.gq(h)&&h.responseXML?h.responseXML:null)&&Z2(a,h)}};
g.qp()&&(d.onFinish=iCa(a,d.onFinish));d.postParams={ic_only:"1"};jCa(d,c);a.M=!0;g.mq(b.Lf,d)}}},jCa=function(a,b){a.method="POST";
a.Lb=a.Lb||{};b.rq&&(a.Lb.ic_coll=b.rq);b.tq&&(a.Lb.ic_xml=b.tq);b.Cp&&(a.Lb.ic_track=b.Cp)},lCa=function(a){var b=new g.V({D:"div"});
g.Cg(b.element,!1);var c=new M2(a.player,b.element,$2(a));g.C(c,b);b.Y(a.u.element);c.kp();return c},$2=function(a){if(!a.J){var b=new l2(a);
g.C(a,b);var c=new g.Z0(a);g.C(a,c);a.J=new YBa(b,c,a.player.N(),a.player.getVideoData(),a.logger,a.player,a.bb)}return a.J},Z2=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ns();if(e){var f=g.Ls();f&&g.ct(g.ro("use_default_events_client")?void 0:g.Ar,e,f,[g.Hs(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=hCa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=y2(h.type,mCa),r=y2(h.style,nCa),t=x2(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=zBa;if(null==x)var A=null;else if(g.Pa(x)){m=[];for(var D=g.q(x),E=D.next();!E.done;E=
D.next()){var H=h(E.value);H&&m.push(H)}A=m}else{var T=h(x);A=T?[T]:[]}f=n&&p?new B2(n,p,r,A,w):null}else f=null}catch(fb){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var P=eCa(h),Qa=null;switch(m.type){case "branding":if(h.player.N().Za)break;h.u.element.appendChild(P);Qa=new T2(P,$2(h),m);break;case "promotion":g.OO(h.player,P,4),Qa=new U2(P,$2(h),m)}Qa&&Qa.kp();if(h=Qa)g.C(a,h),a.H[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.o||(a.o=lCa(a),g.C(a,a.o));if("card"===f.type){c=
a.o;var kb=f&&f.data&&f.data.card_type;h=f.data;if(kb)switch(m=h.tracking||{},m={gB:m.impression,click:m.click,close:m.close,fF:m.teaser_impression,qt:m.teaser_click},P=h.tracking_params||{},Qa=null,kb){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Yc:h.session_data||{},sponsored:h.sponsored||!1,Pe:m,Xh:P.card?g.Hs(P.card):null,cg:P.teaser?g.Hs(P.teaser):null,Vc:P.icon?
g.Hs(P.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,hE:h.image_url,title:h.title,metaInfo:h.meta_info,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};P2(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Yc:h.session_data||{},sponsored:h.sponsored||!1,Pe:m,Xh:P.card?g.Hs(P.card):null,
cg:P.teaser?g.Hs(P.teaser):null,Vc:P.icon?g.Hs(P.icon):null,yp:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};P2(c,f);break;case "productListing":h.signin_url&&(Qa=A2({target:"current",value:h.signin_url}));kb=[];for(var xb=h.offers||[],Wa=0;Wa<xb.length;Wa++)kb.push(new DBa(g.nd(xb[Wa].merchant),g.nd(xb[Wa].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Yc:h.session_data||{},sponsored:h.sponsored||!1,Pe:m,Xh:P.card?g.Hs(P.card):null,cg:P.teaser?g.Hs(P.teaser):null,Vc:P.icon?g.Hs(P.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,jq:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),gV:Qa,fV:h.signin_title?h.signin_title:void 0,eV:h.signin_message?h.signin_message:void 0,offers:kb};P2(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Yc:h.session_data||{},sponsored:h.sponsored||!1,Pe:m,Xh:P.card?g.Hs(P.card):null,cg:P.teaser?g.Hs(P.teaser):null,Vc:P.icon?
g.Hs(P.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,jq:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};P2(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Yc:h.session_data||{},sponsored:h.sponsored||!1,Pe:m,Xh:P.card?g.Hs(P.card):null,cg:P.teaser?g.Hs(P.teaser):null,Vc:P.icon?g.Hs(P.icon):null,yp:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:A2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},P2(c,f)}}else HBa(a.o,f);c=!0}}c&&(e2(a.player),a.Ds())},oCa=function(a,b){var c=!1;
a.o||(a.o=lCa(a),g.C(a,a.o));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(IBa(a.o,e.cardRenderer),c=!0);c&&(c=a.o,d=b.headerText?g.U(b.headerText):"",g.Le(c.Ja,d),c.J&&c.J.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.W=b.trackingParams?g.Hs(b.trackingParams):null,c.H=b.closeButton.infoCardIconRenderer.trackingParams?g.Hs(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Vc=b.icon.infoCardIconRenderer.trackingParams?
g.Hs(b.icon.infoCardIconRenderer.trackingParams):null,e2(a.player),a.Ds())},pCa=function(a,b,c,d,e){if(!a.player.N().Za){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new wBa("openUrl","click",new uBa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.U(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.U(b.subscriberCountText))):(b.subscriberCountText&&(e=g.U(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.U(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.U(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.U(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new B2(c,"branding","branding",f,d);d=eCa(a);a.u.element.appendChild(d);f=new T2(d,$2(a),f);f.kp();g.C(f,f);a.H[c]=f}},iCa=function(a,b){return function(c){for(var d=
[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.ea()||(d.unshift(b),b=g.Ua.apply(window,d),a.P.push(g.op(b)))}},qCa=function(a){return"annotation-editor"===a||"live-dashboard"===a},f2={},g2=null;g.Xa(i2,g.An);g.k=i2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.va)this.progress=0,this.coords=this.o;else if(this.ub())return!1;h2(this);this.startTime=a=g.z();-1==this.va&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Cs();this.Nf("play");-1==this.va&&this.Nf("resume");this.va=1;var b=g.Ta(this);b in f2||(f2[b]=this);gBa();hBa(this,a);return!0};
g.k.stop=function(a){h2(this);this.va=0;a&&(this.progress=1);iBa(this,this.progress);this.Nf("stop");this.Mo()};
g.k.pause=function(){this.ub()&&(h2(this),this.va=-1,this.Nf("pause"))};
g.k.V=function(){0==this.va||this.stop(!1);this.Nf("destroy");i2.Pc.V.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.zv=function(){this.Nf("animate")};
g.k.Nf=function(a){this.dispatchEvent(new jBa(a,this))};
g.Xa(jBa,g.Jl);g.Xa(j2,i2);j2.prototype.A=g.Ma;j2.prototype.zv=function(){this.A();j2.Pc.zv.call(this)};
j2.prototype.Mo=function(){this.A();j2.Pc.Mo.call(this)};
j2.prototype.Cs=function(){this.A();j2.Pc.Cs.call(this)};
g.Xa(k2,j2);k2.prototype.A=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(l2,g.B);l2.prototype.ia=function(a,b,c,d){c=(0,g.y)(c,d||this.u);a=g.ap(a,b,c);this.o.push(a);return a};
l2.prototype.Dr=function(a,b,c,d){c=(0,g.y)(c,d||this.u);a=g.jp(a,b,c);this.o.push(a);return a};
l2.prototype.sb=function(a){g.bp(a);g.qb(this.o,a)};
l2.prototype.V=function(){g.bp(this.o);this.o.length=0;g.B.prototype.V.call(this)};g.u(p2,g.FS);g.k=p2.prototype;g.k.load=function(){g.FS.prototype.load.call(this);if(!q2(this)){var a=g.eG(this.player.getVideoData());if(a)a=o2(a,lBa(this)),r2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",Xe:(0,g.y)(this.hM,this,a),fg:{v:a},withCredentials:!0};this.P&&(a.fg.ptype="embedded");var c=this.player.getVideoData().Gq;c&&(a.Lb={ad_tracking:c});if(b=g.PF(b))if(b=g.Jc(b),b=g.Fc(b))this.B=g.mq(b,a)}}};
g.k.unload=function(){r2(this,null);this.B&&(this.B.abort(),this.B=null);g.FS.prototype.unload.call(this)};
g.k.Hd=function(a,b){if(!q2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=o2(b,"new");r2(this,c);return!0}return null};
g.k.getOptions=function(){return q2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.hM=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=o2(c,lBa(this)))}r2(this,c)};
g.k.ZB=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<rCa.length;f++){var h=Math.abs(b.width-rCa[f]);if(-1==e||d>=h)e=f,d=h}d=sCa[e];this.A&&g.F(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],h=this.H[f],e&&h){var l=h.width*c/h.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Ag(e.element,Math.round(h.width*a.width),f);g.sg(e.element,m,n);g.zn(e.element,tCa);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zn(e.element,sCa);g.I(e.element,d);(e=g.pe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.F(e,"height",f+"px")}}}}};
g.k.UI=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())v2(this,this.u.impressionUrls),(a=g.Ns())&&this.u.visualElement&&g.dt(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.H[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");v2(this,c.impressionUrls);(b=g.Ns())&&g.dt(b,c.visualElement);this.player.N().A&&this.player.la("endscreenelementshown",a)}};
g.k.VI=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.yn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.yn(b,"ytp-ce-shown");this.player.N().A&&this.player.la("endscreenelementhidden",a)}};
g.k.GO=function(a){var b=this;a.target===window&&(new g.G(function(){for(var c in b.o)g.zn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.gD=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.wn(c,"ytp-ce-element");){g.wn(c,"subscribe-label")&&w2(this,a);if(g.wn(c,"ytp-ce-channel-subscribe"))return;c=g.Je(c)}if(!c||g.wn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Uw(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.LP?(w2(this,a),this.QE(),this.player.pauseVideo(),c=g.Jc(t2(this,a.targetUrl)),c=g.Fc(c),g.mK(c,void 0,a.Yc)):(c=this.player.getVideoData().Dc,
c=(0,g.y)(this.BP,this,c,t2(this,a.targetUrl),a.Yc),c=(0,g.y)(this.QE,this,c),w2(this,a,c))}}};
g.k.BP=function(a,b,c){var d=g.Vp(b);a&&d&&(d.v||d.list)?g.Q0(this.player.app,d.v,c,d.list,!1,void 0):g.lK(b,c)};
g.k.Tw=function(a,b){g.wn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.N().o?(new g.G(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),v2(this,b.uI),u2(this,b.id,!0))};
g.k.Uw=function(a,b){g.yn(a.element,"ytp-ce-element-hover");g.yn(a.element,"ytp-ce-force-expand");u2(this,b.id,!1)};
g.k.QE=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var rCa=[346,426,470,506,570,640,853,1280,1920],sCa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),tCa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var vBa={yR:"current",US:"new"};var xBa={CLOSE:"close",WS:"openUrl",wG:"subscribe"},yBa={pR:"click",CLOSE:"close",fS:"hidden",GT:"rollOut",HT:"rollOver",OT:"shown"};B2.prototype.Uc=function(){var a=ABa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var nCa={XQ:"anchored",aG:"branding",CHANNEL:"channel",xR:"cta",iS:"highlightText",xS:"label",PLAYLIST:"playlist",tT:"popup",UT:"speech",wG:"subscribe",iU:"title",VIDEO:"video",vU:"website"},mCa={aG:"branding",hR:"card",DR:"drawer",hS:"highlight",IS:"marker",yT:"promotion",TEXT:"text",xU:"widget"};g.u(H2,g.B);g.k=H2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.BD(a,b,{id:c});a.namespace="annotations_module";d&&this.na.set(a,d);e&&this.oa.set(a,e);g.nM(this.context.G,[a])};
g.k.kp=function(){this.context.u.subscribe("resize",this.lq,this)};
g.k.Ea=function(){return this.element};
g.k.ww=function(a,b,c,d,e,f){if(this.Ca)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.He(this.Ea())};
g.k.lq=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=z2(a);if(f){var h=FBa(f,a.target),l=function(){a.o&&e.context.G.pauseVideo();var m=e.context.videoData.Dc||!1,n=g.Vp(f||"");m&&n&&(n.v||n.list)?g.Q0(e.context.G.app,n.v,b,n.list,!1,void 0):g.mK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);X2(this.context.logger,c,l,d);EBa(f)||(c=g.Ns(),d=b.itct,c&&d&&g.kt(c,g.Hs(d)))}};
g.k.V=function(){this.na.clear();this.oa.clear();g.B.prototype.V.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.C(this,a);return a.element};g.u(M2,H2);g.k=M2.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Bg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.lq=function(){var a=this.isAvailable();g.Cg(this.Ea(),a);g.J(this.context.G.getRootNode(),g.d0.IV_DRAWER_ENABLED,a);e2(this.G)};
g.k.destroy=function(){var a=g.aX(g.SW(this.G));a&&a.pw(!1,void 0);try{this.G.getRootNode().removeChild(this.B)}catch(b){}g.Mo(this.P);g.bp(this.ca);this.fa&&this.fa.dispose();this.C&&this.C.dispose();H2.prototype.destroy.call(this)};
g.k.VG=function(){if(this.A){X2(this.context.logger,R2(this).Pe.close);var a=g.Ns();a&&this.H&&g.kt(a,this.H);L2(this)}};
g.k.jH=function(){g.J(this.B,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.JI=function(){var a=g.Ns(),b=R2(this);b=b?b.Vc:this.Vc;a&&b&&g.it(a,[b])};
g.k.II=function(){var a=g.Ns(),b=R2(this);b=b?b.Vc:this.Vc;a&&b&&g.jt(a,[b])};
g.k.GJ=function(){var a=R2(this);X2(this.context.logger,a.Pe.fF);var b=g.Ns();b&&a&&g.it(b,[a.cg,a.Vc])};
g.k.KI=function(){var a=g.Ns(),b=R2(this);a&&b&&g.jt(a,[b.cg])};
g.k.FJ=function(a){var b=R2(this),c=g.Ns();this.o?a?(a=this.context.logger,X2(a,b.Pe.qt),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.cg&&g.kt(c,b.cg)):(a=this.context.logger,X2(a,b.Pe.qt),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Vc&&g.kt(c,b.Vc)):(a=this.context.logger,X2(a,b.Pe.qt),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Vc&&g.kt(c,this.Vc))};g.u(S2,H2);S2.prototype.kp=function(){H2.prototype.kp.call(this);TBa(this)};
S2.prototype.show=function(){H2.prototype.show.call(this);var a=g.Ns(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.it(a,[g.Hs(b.itct)])};
S2.prototype.hide=function(){H2.prototype.hide.call(this);var a=g.Ns(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.jt(a,[g.Hs(b.itct)])};g.u(T2,S2);
T2.prototype.show=function(){if(!this.isActive){S2.prototype.show.call(this);if(!this.H){g.I(this.Ea(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({D:"img",da:["branding-img","iv-click-target"],O:{"aria-label":"Wasserzeichen des Kanals",src:a.image_url,width:a.image_width,height:a.image_height}});g.Cg(this.u,!1);var b=this.createElement({D:"div",da:["branding-img-container"]});b.appendChild(this.u);this.Ea().appendChild(b);(b=this.annotation.Uc())&&I2(this,this.u,b,this.annotation.id,
a.session_data);XBa(this,a);this.H=!0}g.Cg(this.Ea(),!0);this.isActive=!0;this.u&&UBa(this,this.u)}};
T2.prototype.hide=function(){this.isActive&&(S2.prototype.hide.call(this),g.Cg(this.Ea(),!1),this.isActive=!1)};
T2.prototype.destroy=function(){this.o&&(this.o.dispose(),this.o=null);S2.prototype.destroy.call(this)};g.u(U2,S2);g.k=U2.prototype;g.k.show=function(){this.isActive||(S2.prototype.show.call(this),this.M||(ZBa(this),this.M=!0),g.Cg(this.Ea(),!0),g.Rm(function(){g.yn(this.Ea(),"iv-promo-inactive")},100,this),this.Ea().removeAttribute("aria-hidden"),this.isActive=!0,W2(this),$Ba(this),aCa(this,this.F))};
g.k.hide=function(){this.isActive&&(g.I(this.Ea(),"iv-promo-inactive"),this.isActive=!1,this.Ea().setAttribute("aria-hidden","true"))};
g.k.ww=function(a,b,c,d,e,f){return this.isCollapsed?!1:S2.prototype.ww.call(this,a,b,c,d,e,f)};
g.k.cI=function(a){this.J=!0;V2(this,500,a)};
g.k.bI=function(){this.J=!1;bCa(this)};
g.k.UH=function(a){a.stopPropagation();this.hide()};
g.k.VH=function(a){a.stopPropagation();W2(this);this.isCollapsed=!0;g.I(this.Ea(),"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();S2.prototype.destroy.call(this)};g.u(Y2,g.FS);g.k=Y2.prototype;g.k.Hd=function(a,b){if(!qCa(this.player.N().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Y0(b);c&&Z2(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(KBa(this.o,b),e2(this.player)),!0}return null};
g.k.getOptions=function(){return qCa(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ds=function(){if(this.B){var a=g.KG(this.player).getVideoContentRect(!0);g.Ag(this.B.element,a.width,a.height);g.sg(this.B.element,a.left,a.top)}if(this.o){var b=this.player.xk();a=this.o;b=b.width;g.J(a.B,"iv-drawer-small",426>=b);g.J(a.B,"iv-drawer-big",1280<=b)}};
g.k.EJ=function(a){fCa(this,a.state);g.S(a.state,2)&&(this.vo()&&this.TB()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.pw(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.F=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.gq(h)&&h.responseXML?h.responseXML:null)&&(Z2(b,h),g.I(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.FS.prototype.load.call(this);fCa(this,g.mI(this.player));this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.qp()&&(a=iCa(this,a));var e={format:"XML",Xe:a,onError:function(){b.F=null},
fg:{}};c.isPharma&&(e.fg.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.N().M.get(d);f&&jCa(e,f);f=f&&(f.tq||f.rq);if(!c.fq||f)c.Lf?gCa(this,c.Lf,e):(this.A=function(){b.Ha(e)},this.player.addEventListener("videodatachange",this.A));
g.OO(this.player,this.B.element,4);this.Ds();(f=g.fG(c))&&oCa(this,f);(f=g.gG(c))&&f.featuredChannel&&pCa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Ha=function(a){var b=this.player.getVideoData();b.Lf&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),gCa(this,b.Lf,a))};
g.k.unload=function(){g.hX(this.player,"annotations_module");for(var a=g.q(Object.keys(this.H)),b=a.next();!b.done;b=a.next())this.H[b.value].destroy();this.J=null;this.o&&(this.o.destroy(),this.o=null,e2(this.player));this.M=!1;this.F&&(this.F.abort(),this.F=null);this.H={};this.u.hide();g.FS.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.QD=function(a){a===this.player.getVideoData().videoId&&(this.loaded?kCa(this):this.load())};
g.k.vo=function(){return!!this.o&&this.o.isAvailable()};
g.k.TB=function(){this.vo();return!!this.o&&this.o.A};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.vo();this.o&&(a?c?K2(this.o,c,b):K2(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):L2(this.o))};
g.k.pw=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.V=function(){this.player.N().M.unsubscribe("vast_info_card_add",this.QD,this);g.yn(this.player.getRootNode(),g.d0.IV_DRAWER_OPEN);for(var a=this.P,b=0,c=a.length;b<c;b++)g.rp(a[b]);this.P.length=0;g.FS.prototype.V.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.C(this,a);return a.element};g.vX.annotations_module=Y2;g.vX.creatorendscreen=p2;})(_yt_player);
