(function(g){var window=this;var d3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.GE(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},e3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},uCa=function(a,b){var c=new g.FE;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},vCa=function(){this.u=[];
this.o=[]},f3=function(a,b){switch(b.kind){case "asr":wCa(b,a.u);
break;default:wCa(b,a.o)}},wCa=function(a,b){g.gb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},g3=function(){g.B.call(this);
this.u=new vCa;this.B=[]},h3=function(a,b,c){g3.call(this,a);
this.audioTrack=c;this.o=null;this.B=b.yu},i3=function(){this.segments=[]},xCa=function(a,b){var c=g.Ab(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.pb(a.segments,c),g.pb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.wb(a.segments,c,0,b),g.wb(a.segments,c+1,0,b)))},j3=function(a,b,c,d,e,f){g.B.call(this);
this.policy=a;this.player=b;this.P=c;this.F=d;this.C=e;this.J=f;this.M=this.player.N();this.B=new i3;this.u=this.A=this.o=null;this.H=new g.G(this.HB,1E3,this);this.events=new g.ns(this);g.C(this,this.H);g.C(this,this.events);this.events.K(b,"SEEK_COMPLETE",this.iC);this.iC();this.HB()},yCa=function(a,b){var c=g.Yv(b,a.policy,{}).Uc(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Qr(c,d,3,100).then(function(e){a.ea();var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.Oz(e);h?(e=g.Yv(a.A,a.policy,{}),f=a.A,g.Uv(f.u,e,h),f.requestId=e.get("req_id"),yCa(a,a.A)):(f||null==a.F||(h=a.A.o[0],a.C?a.F(e.response,1E3*(h.startTime+a.player.Vb())):a.F(e.responseText,1E3*(h.startTime+a.player.Vb()))),a.A=null,a.u=null)});
a.A=b;xCa(a.B,a.A.o[0].u)},k3=function(a,b){g3.call(this,b.N());
this.ga=a;this.G=b;this.o=null;this.A=!1;this.C=g.wC(this.G.N())&&!this.ga.isManifestless},zCa=function(a,b){var c=[],d;
for(d in a.ga.o)if(a.ga.o.hasOwnProperty(d)){var e=a.ga.o[d];if(g.qX(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.FE({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},ACa=function(a,b){return null!=b&&b in a.ga.o?a.ga.o[b]:null},BCa=function(a,b,c){var d=[],e;
for(e in a.ga.o)if(a.ga.o.hasOwnProperty(e)){var f=a.ga.o[e];if(g.qX(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},l3=function(a,b,c,d,e){g3.call(this,e||null);
this.videoId=b;this.hB=d;this.C={};this.o=null;b=c||g.Vp(a).hl||"";b=b.split("_").join("-");this.A=g.Xp(a,{hl:b})},m3=function(a,b,c,d,e,f,h){var l={};
g.Va(l,b);g.Va(l,a.params);g.Va(l,c);var m={};g.Va(m,b.ac);a.params.ac&&g.Va(m,a.params.ac);g.Va(m,c.ac);l.ac=m;g.V.call(this,{D:"div",I:"caption-window",O:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},L:[{D:"span",I:"captions-text",O:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.U=!1;this.u=a;this.X=this.W=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.F=null;this.maxWidth=.96*e;this.Ca=.96*f;this.o=l;this.Ra=
c;this.B=this.ba("captions-text");this.Ja=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.aa=d/360*16;this.type=0;this.oa=this.aa*CCa(m);a=new g.xs(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.OJ,this);a.subscribe("dragmove",this.NJ,this);a.subscribe("dragend",this.MJ,this);this.xa=this.ra=0;b="";this.o.windowOpacity&&(a=g.X0(this.o.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.windowOpacity+
")");a={"background-color":b,display:!1===this.o.isVisible?"none":"","text-align":DCa[this.o.textAlign]};this.Ja&&(a["border-radius"]=b?this.oa/8+"px":"");if(this.A=2===this.u.params.o||3===this.u.params.o)b=this.element,c="vertical-rl",1===this.o.A&&(c="vertical-lr"),g.we&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.F(b,"-o-writing-mode",c),g.F(b,"-webkit-writing-mode",c),g.F(b,"writing-mode",c),g.F(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.u.params.o&&(g.F(b,"text-orientation",
""),g.F(b,"transform","rotate(180deg)"));g.F(this.element,a);switch(this.o.lg){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},CCa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},ECa=function(a,b){var c={},d=b.background?b.background:a.o.ac.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.o.ac.backgroundOpacity;d=g.X0(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ja&&(c["box-decoration-break"]="clone",c["border-radius"]=a.oa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*CCa(b)+"px";d=1;e=b.color||a.o.ac.color;if(b.color||null!=b.textOpacity)e=g.X0(e),d=null==b.textOpacity?a.o.ac.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.Du&&(h=e=b.Du);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Xj()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.ac.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Bg&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.tI&&(c.visibility="hidden");1===b.dB&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.AC||g.BC,3===a.u.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Tg||2===b.Tg||3===b.Tg||4===b.Tg||5===b.Tg)if(g.AC)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Tg){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},FCa=function(a){a.F=g.De("SPAN");
g.F(a.F,{display:"block"});g.I(a.F,"caption-visual-line");a.B.appendChild(a.F)},GCa=function(a,b){var c=g.De("SPAN");
g.F(c,{display:"inline-block","white-space":"pre-wrap"});g.F(c,ECa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.F(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.F(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},HCa=function(a,b,c){a.U=a.U||!!c;
var d={};g.Va(d,a.o.ac);g.Va(d,c||b.o);g.Va(d,a.Ra.ac);(c=!a.F)&&FCa(a);for(var e=a.W&&a.X&&g.Xb(d,a.X)?a.W:GCa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(FCa(a),e=GCa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ee(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.AC||!g.og(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.og(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.ye?g.F(e,m,"1em"):g.F(e,m,"0.5em")))}a.X=d;a.W=e;a.C.push(b)},n3=function(a,b,c,d,e,f,h){m3.call(this,a,b,c,d,e,f,h);
this.type=1},o3=function(a,b,c,d,e,f,h){m3.call(this,a,b,c,d,e,f,h);
this.type=2;this.H=[];this.P=this.M=this.ca=0;this.S=NaN;this.Ga=0;this.bb=null;this.fa=new g.G(this.MN,433,this);g.I(this.element,"ytp-caption-window-rollup");g.C(this,this.fa);g.F(this.element,"overflow","hidden")},ICa=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},JCa=function(a){if(isNaN(a.S)){var b=a.o.Ti;
if(b){var c=g.De("SPAN");g.Le(c,"\u2013".repeat(b));g.F(c,ECa(a,a.o.ac));a.B.appendChild(c);a.S=c.offsetWidth;a.B.removeChild(c)}else a.S=0}return a.S},KCa=function(a,b){if(!b)return"";
a.A&&1!==a.u.params.A&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},LCa=function(a){a.H=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.u,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.M=d;a.P=Math.max(JCa(a),a.Ga,ICa(a,a.B))},MCa=function(a,b){LCa(a);
var c=a.H.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.M-c;if(c!==a.ca){var d=0<c&&0===a.ca;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),a.fa.kb());g.F(a.B,"transform",KCa(a,c));a.ca=c}LCa(a)},p3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.BD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=h},q3=function(a,b,c,d,e){g.BD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},NCa=function(a){var b="_"+r3++;
return new q3(0,0x8000000000000,0,b,a)},PCa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Kc){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=OCa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new p3(a,b,e,c,l,d,m)}switch(m.Kc){case 9:case 10:m.Tg=1;break;case 11:m.Tg=2;break;case 12:m.Tg=3;break;case 13:m.Tg=4;break;case 14:m.Tg=5}return new p3(a,b,e,c,l.textContent||"",d,m)},OCa=function(a,b,c,d,e){var f=g.Xj(),h=
f?g.De("DIV"):g.De("RUBY"),l=g.De("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.De("DIV"):g.De("RP");a.textContent=b;h.appendChild(a);b=f?g.De("DIV"):g.De("RT");b.textContent=c;h.appendChild(b);c=e.Kc;if(10===c||11===c||12===c||13===c||14===c)if(g.F(b,"text-emphasis-style","filled circle"),g.F(b,"text-emphasis-color","currentcolor"),g.F(b,"webkit-text-emphasis","filled circle"),11===e.Kc||13===e.Kc)g.F(b,"webkit-text-emphasis-position","under left"),g.F(b,"text-emphasis-position","under left");c=!0;if(4===e.Kc||7===e.Kc||12===e.Kc||14===
e.Kc)g.F(h,"ruby-position","over"),g.F(h,"-webkit-ruby-position","before");else if(5===e.Kc||6===e.Kc||11===e.Kc||13===e.Kc)g.F(h,"ruby-position","under"),g.F(h,"-webkit-ruby-position","after"),c=!1;e=f?g.De("DIV"):g.De("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.F(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.F(f,"display","none"),f=f.nextElementSibling,g.F(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",
transform:"translateX(-50%)",width:"400%"}),g.F(h.lastElementChild,"display","none"),d?(g.F(h,"padding-top","0.6em"),g.F(f,"top","0")):(g.F(h,"padding-bottom","0.6em"),g.F(f,"bottom","0")));return h},s3=function(){g.B.apply(this,arguments)},t3=function(a){s3.call(this);
this.F=a;this.B={};this.M={};this.P={};this.C="_"+r3++;this.J={};this.u=this.o=null;this.H=!0},u3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},v3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},w3=function(a,b){var c=u3(a,b);
return void 0!==c?c:null},y3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return x3.test(c),c},QCa=function(a,b){var c={},d=b.getAttribute("ws");
g.Va(c,d?a.P[d]:a.F);d=w3(b,"mh");null!=d&&(c.wm=d);d=w3(b,"ju");null!=d&&(c.textAlign=d);d=w3(b,"pd");null!=d&&(c.o=d);d=w3(b,"sd");null!=d&&(c.A=d);d=y3(b,"wfc");null!=d&&(c.windowColor=d);d=u3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},RCa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Va(c,a.M[d]);d=w3(b,"ap");null!=d&&(c.lg=d);d=u3(b,"cc");null!=d&&(c.Ti=d);d=u3(b,"ah");null!=d&&(c.Cf=d);d=u3(b,"rc");null!=d&&(c.u=d);d=u3(b,"av");null!=d&&(c.Wg=d);return c},SCa=function(a,b,c,d){var e={};
g.Va(e,RCa(a,b));g.Va(e,QCa(a,b));d?g.Xb(e,a.F)?(d=a.C,e=a.F):d="_"+r3++:d=b.getAttribute("id")||"_"+r3++;a=u3(b,"t")+c;b=u3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.Ti,e.Ti=c;return new q3(a,b,0,d,e)},z3=function(a){s3.call(this);
this.F=a;this.o=new Map;this.B=new Map;this.C=new Map;this.u=new Map},A3=function(a){a=g.Zd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},TCa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.Ti=b);if(2===f.o||3===f.o)b=f.u,f.u=f.Ti,f.Ti=b;return new q3(c,d,0,e,f)},C3=function(){this.A=this.time=this.mode=this.u=0;
this.B=new B3(this);this.C=new B3(this);this.o=[];this.clear()},VCa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Zj:a,
Qi:b,result:0};a=UCa[a];b=UCa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Qi===d;if(d)return{Zj:a,Qi:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Zj:a,Qi:b,result:2};return{Zj:a,Qi:b,result:3}},XCa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,WCa(a.B,b,c,d))},YCa=function(a,b){a.o.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?XCa(a,d.Ez,d.Fz,b):1===d.type&&a.u&496&&WCa(a.C,d.Ez,d.Fz,b);a.o.length=0},D3=function(){this.type=0},E3=function(){this.state=this.Qi=this.Zj=0},ZCa=function(){this.timestamp=this.o=0},F3=function(a){this.C=a;
this.A=[];this.o=this.u=this.row=0;this.style=new D3;for(a=this.B=0;15>=a;a++){this.A[a]=[];for(var b=0;32>=b;b++)this.A[a][b]=new ZCa}},G3=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.A[m][p];
if(0!==r.o){0===c&&(c=m,d=p);n=String.fromCharCode(r.o);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.o||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.A[h][m],r=p.o,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},dDa=function(a,b){switch(a){case 0:return $Ca[(b&127)-32];
case 1:return aDa[b&15];case 2:return bDa[b&31];case 3:return cDa[b&31]}return 0},H3=function(a){return a.A[a.row][a.u]},I3=function(a,b,c){2<=b&&1<a.u&&(--a.u,H3(a).o=0);
var d=H3(a);d.timestamp=a.C.time+0;d.o=dDa(b,c);32>a.u&&a.u++},eDa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.A[b+e][f],l=a.A[c+e][f];
h.o=l.o;h.timestamp=l.timestamp}},J3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},K3=function(a){a.row=0<a.o?a.o:1;
a.u=1;J3(a,0,15)},L3=function(a){this.A=a;
this.C=0;this.style=new D3;this.F=new F3(this.A);this.H=new F3(this.A);this.text=new F3(this.A);this.u=this.F;this.B=this.H;this.o=this.u},M3=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(G3(d,c),K3(a.u),K3(a.B),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.B;e?d.u=1:d.o!==b&&(d.o>b?(G3(d,c),J3(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},fDa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.B},gDa=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.A.mode=1<<a.o.B},B3=function(a){this.u=a;
this.C=0;this.A=new L3(this.u);this.F=new L3(this.u);this.o=new E3;this.B=this.A},WCa=function(a,b,c,d){a.o.update();
b=VCa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Zj;c=b.Qi;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&I3(a,0,b),c&96&&I3(a,0,c),0!==b&&0!==c&&3===a.style.type&&G3(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.Zj=e,b.Qi=c,b.state=2,b=e&8?a.F:a.A,a.B=b,a.u.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,h=1+d-c.o;eDa(c,h,f,c.o);b=f;e=c.o;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));J3(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:I3(b.o,0,32);break a;case 48:57===c?(d=b.o,H3(d).o=0,32>d.u&&d.u++):I3(b.o,1,c&15)}break;case 2:c&32&&I3(b.o,2,c&31);break;case 3:c&32&&I3(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:fDa(b);
break;case 33:d=b.o;1<d.u&&(--d.u,H3(d).o=0);break;case 36:d=b.o;b=H3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]===b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:M3(b,2,d);break;case 38:M3(b,3,d);break;case 39:M3(b,4,d);break;case 40:I3(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.B;break;case 42:d=b.text;d.o=15;d.style.set(4);K3(d);gDa(b);break;case 43:gDa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:G3(a,d)}J3(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;G3(a,d);eDa(a,b,b+1,a.o-1);J3(a,a.row,1)}break;case 46:J3(b.B,0,15);break;case 47:G3(b.u,d),b.B.updateTime(b.A.time+0),d=b.B,b.B=b.u,b.u=d,fDa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},hDa=function(){},N3=function(a,b,c){this.J=a;
this.H=c;this.version=this.F=this.B=this.o=0;this.u=new DataView(this.J);this.A=[]},O3=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},P3=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},Q3=function(a,b){s3.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.o=new C3;this.o.u=1<<this.track},R3=function(a){if("string"===typeof a)return!1;
a=new N3(a,8,0);return iDa(a)},iDa=function(a){if(!(a.o<a.u.byteLength)||1380139777!==P3(a))return!1;
a.version=O3(a);if(1<a.version)return!1;O3(a);O3(a);O3(a);return!0},S3=function(){s3.call(this)},jDa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Bg=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new p3(b,c,d,e.id,p.nodeValue,f||0<n,g.Vb(l)?void 0:l),m.push(p),e.o.push(p);else{var r={};g.Va(r,l);jDa(a,b,c,d,e,!0,p,r,m)}}},T3=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},kDa=function(a,b,c,d){d=Object.assign({wm:0},d);
return new q3(a,b,c,"_"+r3++,d)},U3=function(a){g.B.call(this);
this.u=a;this.o=null},mDa=function(a){var b={};
if(a=e3(a))b.lang=a,lDa.test(a)&&(b.o=1);return b},X3=function(a){g.FS.call(this,a);
this.G=a;this.A=this.G.N();this.videoData=this.G.getVideoData();this.Ga=g.KG(this.G);this.B={ac:{}};this.F={ac:{}};this.S=[];this.M={};this.fa={};this.W=!1;this.xa=g.xva(this.videoData,this.G);this.Ja=!!this.videoData.captionTracks.length;this.Ra=!!this.videoData.un;this.oa="3"===this.A.controlsType;this.u=this.H=this.J=this.ca=this.ra=null;this.na=new U3(this.A);this.o=null;this.X=new g.ns(this);var b=null,c=g.fo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Pn(c));this.storage=b;b=
a.app.C;c=!(!b||!b.wp());this.Ca=!(!b||!b.vl());this.C=this.oa&&c&&!this.xa;this.P=!this.C&&this.oa&&this.Ca&&this.xa;g.C(this,this.na);this.C?this.aa=this.U=null:(this.U=new g.nn(this.uF,void 0,this),g.C(this,this.U),this.aa=new g.G(this.kP,2E3,this),g.C(this,this.aa));g.C(this,this.X);this.C||this.X.K(a,"resize",this.my);this.X.K(a,"onPlaybackAudioChange",this.CL);this.X.K(a,g.ED("captions"),this.PJ,this);this.X.K(a,g.FD("captions"),this.QJ,this);V3(this,W3(this,"display-settings")||{})},Y3=function(a){if(1===
a.A.Wh||1===a.videoData.Wh||"alwayson"===g.IF(a.videoData,"yt:cc"))return!0;
if(2===a.A.Wh){var b=W3(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().A;return"ON"===c||"on"===g.IF(a.videoData,"yt:cc")},Z3=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.u||"FORCED_ON"===c.A},a4=function(a,b){if(a.u){if(a.H&&a.H.C)return a.H.C;
var c=b;c||(c=a.Ra?!1:a.Ja?!1:!0);c=a.u.vk(c);for(var d=[a.videoData.captionsLanguagePreference,a.A.captionsLanguagePreference,g.IF(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(e3(c[f])===d[e])return c[f];return a.H&&a.H.B?a.H.B:(d=c.find(function(h){return h.isDefault}))?d:c[0]||$3(a)}return null},$3=function(a){return a.H&&a.H.u},b4=function(a){var b=$3(a);
return!!b&&a.o===b},nDa=function(a,b){for(var c=a.G.app.C.Ea().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},d4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.W=c,a.W&&c4(a,"module-enabled",!!b));a.o=b;Z3(a)&&(a.o=$3(a));a.load()},oDa=function(a,b){var c=a.Ga.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&lDa.test(d)&&(b.params.o=1);d=a.Ga.getPlayerSize();switch(null!=b.params.wm?b.params.wm:1<b.o.length?1:0){case 1:return new n3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);case 2:return new o3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);default:return new m3(b,a.B,a.F,c,d.width,d.height,a.A.experiments)}},V3=function(a,b,c){c=void 0===c?!1:c;
var d=e4.ac;a.B={};g.Va(a.B,e4);a.B.ac={};g.Va(a.B.ac,d);a.F={ac:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;x3.test(f);e.ac.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;x3.test(f);e.ac.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||e4.windowColor;x3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ac.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.ac.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Bg?3:d.bold?1:d.Bg?2:0);f=f.ac;switch(e){case 1:f.bold=!0;delete f.Bg;break;case 2:delete f.bold;f.Bg=!0;break;case 3:f.bold=!0;f.Bg=!0;break;default:delete f.bold,delete f.Bg}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ac.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=e4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.ac.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ac.fontFamily=f;a.loaded&&a.my();c&&c4(a,"display-settings",b)},qDa=function(a,b){if(b&&!a.J){var c=NCa({o:0,
lang:"de"});a.J=[c,new p3(c.start,c.end-c.start,0,c.id,"So werden die Untertitel mit der aktuellen Konfiguration aussehen.")];g.nM(a.player,a.J)}else!b&&a.J&&(pDa(a,a.J),a.J=null)},pDa=function(a,b){g.oM(a.player.app,b,void 0);
g.Gb(b,function(c){g.qb(this.S,c)},a);
a.U.kb()},W3=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},c4=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.SS.prototype.xn=g.ca(11,function(){for(var a=g.pe(document,"track",void 0,this.o),b=0;b<a.length;b++)g.He(a[b])});
g.TS.prototype.xn=g.ca(10,function(){this.o.xn()});
g.SS.prototype.wp=g.ca(9,function(){return!!this.o.textTracks});
g.TS.prototype.wp=g.ca(8,function(){return this.o.wp()});
g.SS.prototype.on=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.TS.prototype.on=g.ca(6,function(a){this.o.on(a)});
g.MS.prototype.vl=g.ca(5,function(){});
g.SS.prototype.vl=g.ca(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.TS.prototype.vl=g.ca(3,function(){return this.o.vl()});
g.qw.prototype.Zq=g.ca(1,function(){return 0});
g.yz.prototype.Zq=g.ca(0,function(a){return(a=this.kh(a))?a.o:0});
var lDa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;vCa.prototype.vk=function(a){return a?this.o.concat(this.u):this.o};
g.u(g3,g.B);g.k=g3.prototype;g.k.vk=function(a){return this.u.vk(a)};
g.k.Gr=function(){};
g.k.Hr=function(){};
g.k.Ki=function(){};
g.k.dm=function(){return""};
g.k.gE=function(){return!1};
g.k.V=function(){this.Ki();g.B.prototype.V.call(this)};
g.u(h3,g3);h3.prototype.Gr=function(a,b,c){var d=this;this.ea();b=this.dm(a,b);this.Ki();this.o=g.mq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
h3.prototype.Hr=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())f3(this.u,c.value);a()};
h3.prototype.dm=function(a,b){var c=a.Uc(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.Xj()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=e3(a));return g.Xp(c,d)};
h3.prototype.Ki=function(){this.o&&this.o.abort()};
i3.prototype.contains=function(a){a=g.Ab(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
i3.prototype.length=function(){return this.segments.length/2};
g.u(j3,g.B);g.k=j3.prototype;g.k.V=function(){g.B.prototype.V.call(this);this.u&&this.u.cancel()};
g.k.iC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Vb();var b=this.o;this.o=g.db(this.P.ji(a).o);b!==this.o&&this.J&&this.J()};
g.k.reset=function(){this.B=new i3;this.u&&(this.u.cancel(),this.u=null)};
g.k.HB=function(){this.ea();var a;if(a=null!=this.o)a=this.o,a=a.o.Bi(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.bj(),a.o[0].duration?(this.B.contains(a.o[0].u)||yCa(this,a),this.o=g.db(a.o)):!g.Q(this.M.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.F&&this.o.F+this.player.Vb()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.H.start()};
g.u(k3,g3);g.k=k3.prototype;g.k.Gr=function(a,b,c){var d=this;this.Ki();b=ACa(this,a.getId());b||(b=a.languageCode,b=this.ga.isManifestless?BCa(this,b,"386"):BCa(this,b));if(b){var e=1E3*(b.index.Zq(b.index.ug())-b.index.Zd(b.index.ug()));this.o=new j3(new g.pv,this.G,b,function(f,h){c(f,a,h,e)},this.C||g.fv(b.info),function(){d.o&&d.o.reset();
d.A=!0})}};
g.k.gE=function(){var a=this.A;this.A=!1;return a};
g.k.Hr=function(a){var b;this.C?b=[new g.FE({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.FE({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ga.isManifestless?zCa(this,"386"):zCa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())f3(this.u,c.value);a()};
g.k.Ki=function(){this.o&&(this.o.dispose(),this.o=null)};
g.k.dm=function(){return""};
g.u(l3,g3);l3.prototype.Gr=function(a,b,c){var d=this;this.ea();b=this.dm(a,b);this.Ki();this.o=g.mq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
l3.prototype.Hr=function(a){var b=this,c=this.A,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.hB&&(d.asrs=1);c=g.Xp(c,d);this.Ki();this.o=g.mq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");f3(b.u,new g.FE({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.C[m.languageCode]=m.languageName,b.B.push(m)}a()},
withCredentials:!0})};
l3.prototype.dm=function(a,b){var c=this.A,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=e3(a));return c=g.Xp(c,d)};
l3.prototype.Ki=function(){this.o&&this.o.abort()};
var x3=/^#(?:[0-9a-f]{3}){1,2}$/i;var DCa=["left","right","center","justify"];g.u(m3,g.V);g.k=m3.prototype;g.k.OJ=function(a,b){var c=g.yg(this.element,this.element.parentElement);this.ra=a-c.x;this.xa=b-c.y;g.I(this.element,"ytp-dragging")};
g.k.NJ=function(a,b){var c=g.Bg(this.element),d=a-this.ra-.02*this.playerWidth,e=b-this.xa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Zd(f,0,2));var h=(e+c.height/2)/this.Ca*3;h=Math.floor(g.Zd(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Zd(d,0,1);c=(e+h/2*c.height)/this.Ca;c=100*g.Zd(c,0,1);this.u.params.lg=l;this.u.params.Wg=c;this.u.params.Cf=d;this.o.lg=l;this.o.Wg=c;this.o.Cf=d;this.LE()};
g.k.MJ=function(){g.yn(this.element,"ytp-dragging")};
g.k.LE=function(){this.rl(this.C)};
g.k.rl=function(a){var b=Math.min(this.BA(),this.maxWidth),c=this.AA(),d="";3===this.u.params.o&&(d="rotate(180deg)");g.F(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.qu(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.o.Cf+2;d=this.o.lg;switch(d){case 0:case 3:case 6:b=this.o.ac.fontSizeIncrement;!g.Q(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.o.o&&3!==this.o.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.o.Wg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.F(this.element,a)};
g.k.qu=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.U||this.C.length>b)b=0,this.U=!1,this.C=[],this.F=this.X=this.W=null,g.Fe(this.B);for(;b<a.length;b++)HCa(this,a[b])};
g.k.BA=function(){return 0};
g.k.AA=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.u(n3,m3);n3.prototype.qu=function(a){var b=this.u.o;m3.prototype.qu.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Va(d,c.o);g.Va(d,rDa);var e=c.o;var f=d}HCa(this,c,d)}};
var rDa={tI:!0};g.u(o3,m3);g.k=o3.prototype;g.k.LE=function(){g.qn(this.fa)};
g.k.MN=function(){g.yn(this.element,"ytp-rollup-mode");this.rl(this.bb,!0)};
g.k.AA=function(){return this.A?this.P:this.M};
g.k.BA=function(){return this.A?this.M:this.P};
g.k.rl=function(a,b){this.bb=a;if(this.u.params.u){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.Ga=this.P;this.M=this.P=0;m3.prototype.rl.call(this,a);MCa(this,b);m3.prototype.rl.call(this,a)}else m3.prototype.rl.call(this,a)};g.u(p3,g.BD);p3.prototype.toString=function(){return g.BD.prototype.toString.call(this)};g.u(q3,g.BD);q3.prototype.toString=function(){return g.BD.prototype.toString.call(this)};
var r3=0;g.u(s3,g.B);s3.prototype.A=function(){return[]};
s3.prototype.reset=function(){};g.u(t3,s3);t3.prototype.reset=function(){this.J={};this.u=this.o=null;this.H=!0};
t3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Va(l,this.B[m]);m=v3(c,"b");null!=m&&
(l.bold=m);m=v3(c,"i");null!=m&&(l.Bg=m);m=v3(c,"u");null!=m&&(l.underline=m);m=w3(c,"et");null!=m&&(l.charEdgeStyle=m);m=w3(c,"of");null!=m&&(l.offset=m);m=y3(c,"bc");null!=m&&(l.background=m);m=y3(c,"ec");null!=m&&(l.Du=m);m=y3(c,"fc");null!=m&&(l.color=m);m=w3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=u3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=u3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=u3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=w3(c,"rb");null!=m&&10!==m&&0!==m&&(l.Kc=
10<m?m-1:m);c=w3(c,"hg");null!=c&&(l.dB=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.P[d]=QCa(this,c);break;case "wp":d=c.getAttribute("id"),this.M[d]=RCa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=SCa(this,d,e,!1);(d=this.J[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.J[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.C;m=!!v3(d,
"a");n=(u3(d,"t")||0)+n;var p=u3(d,"d")||5E3;m||(!this.H&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.B[t]:null;var w=Array.from(d.childNodes);w.length&&(this.H=null!=d.getAttribute("d"));for(var x=0;x<w.length;x++){var A=w[x],D=void 0;0<x&&(m=!0);var E=void 0;1===A.nodeType&&(E=A);if(E&&"s"===E.tagName){if((A=(A=E.getAttribute("p"))?this.B[A]:null)&&A.Kc&&(1===A.Kc?(A=w.slice(x,x+4),4===A.length&&
(D=PCa(n,p,l,m,r,A,this.B),x+=3)):D=PCa(n,p,l,m,r,[E],this.B)),!D){var H=E;D=n;E=p;A=l;var T=m,P=r,Qa=H.textContent?H.textContent:"",kb=H.getAttribute("p");kb=kb?this.B[kb]:null;H=u3(H,"t")||0;D=new p3(D+H,E-H,P,A,Qa,T,kb)}}else D=new p3(n,p,r,l,A.textContent||"",m,t);h.push(D);this.u=D}if(0<h.length)for(h[0].windowId===this.C&&(this.o=SCa(this,d,e,!0),c.push(this.o)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.o.id,this.o.o.push(h),c.push(h)}e=c}else e=[];return e};var sDa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(z3,s3);z3.prototype.reset=function(){this.u.clear()};
z3.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.o.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.Bg=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.Du=A3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=A3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=A3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Kc=10<l?l-1:l,h.Tg=sDa.get(h.Kc));f.hgHorizGroup&&(h.dB=f.hgHorizGroup);this.o.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.F),void 0!==f.mhModeHint&&(h.wm=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.A=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=A3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.Cf=f.ahHorPos),void 0!==f.apPoint&&(h.lg=f.apPoint),void 0!==f.avVerPos&&(h.Wg=f.avVerPos),void 0!==f.ccCols&&(h.Ti=f.ccCols),void 0!==f.rcRows&&(h.u=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=TCa(this,m,e,f,h),d.push(e),this.u.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+r3++,l=TCa(this,m,e,f,h),d.push(l),this.u.set(h,l));0===f&&(f=5E3);l=this.u.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.o.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],x=w.utf8;if(x){var A=w.tOffsetMs||0,D=null;w.pPenId&&(D=this.o.get(w.pPenId));if(2===(null!=l.params.wm?l.params.wm:1<l.o.length?1:0)&&n&&"\n"===x)continue;if(w=D&&1===D.Kc)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var E=r[w+1].pPenId;(E=this.o.get(E))&&E.Kc&&2===E.Kc?(E=r[w+2].pPenId,E=this.o.get(E),!E||!E.Kc||3>E.Kc?w=!1:(E=r[w+3].pPenId,w=(E=this.o.get(E))&&
E.Kc&&2===E.Kc?!0:!1)):w=!1}if(w){A=r[m+1].utf8;w=r[m+3].utf8;E=r[m+2].utf8;var H=this.o.get(r[m+2].pPenId);x=OCa(x,A,E,w,H);n=new p3(e,f,p,h,x,n,D);m+=3}else n=new p3(e+A,f-A,p,l.id,x,n,D||t);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};C3.prototype.clear=function(){this.A=this.time=this.mode=0;this.o=[];this.reset()};
C3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var UCa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];D3.prototype.set=function(a){this.type=a};
D3.prototype.get=function(){return this.type};
E3.prototype.clear=function(){this.state=0};
E3.prototype.update=function(){this.state=2===this.state?1:0};
E3.prototype.isValid=function(){return 0!==this.state};
E3.prototype.matches=function(a,b){return this.isValid()&&a===this.Zj&&b===this.Qi};
ZCa.prototype.reset=function(){this.timestamp=this.o=0};
F3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
F3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
F3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.o=0;this.u=this.row=1};
var $Ca=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],aDa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],bDa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],cDa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];L3.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.u=this.F;this.B=this.H;this.o=this.u;var c=(a<<2)+(b<<1);this.F.reset(c);this.H.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
B3.prototype.reset=function(a){this.C=a;this.o.clear();this.B=this.A;this.A.reset(a,0);this.F.reset(a,1)};hDa.prototype.C=function(){};g.u(N3,hDa);N3.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+r3++;c=c/1E3-this.H;d=d/1E3-this.H;a=new q3(c,d-c,5,f,{textAlign:0,lg:0,Cf:2.5*b,Wg:5.33*a});e=new p3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.u(Q3,s3);Q3.prototype.A=function(a){a=new N3(a,a.byteLength,this.u);if(iDa(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.B=P3(a)*(1E3/45):1===a.version&&(a.B=4294967296*P3(a)+P3(a)),a.F=O3(a);0<a.F;a.F--){var b=O3(a),c=O3(a),d=O3(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,Ez:c,Fz:d,order:b.o.length}))}YCa(this.o,a);return a.A}return[]};
Q3.prototype.reset=function(){this.o.clear()};g.u(S3,s3);
S3.prototype.A=function(a,b){for(var c=[],d=a.split(tDa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!uDa.test(f)){var l=f4.exec(f);if(l&&4<=l.length){var m=T3(l[1]),n=T3(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",w=null,x="";l.textAlign=2;p=g.q(p);for(var A=p.next();!A.done;A=p.next())if(A=A.value.split(":"),2===A.length){var D=A[1];switch(A[0]){case "line":A=D.split(",");A[0].endsWith("%")&&(r=A[0],l.Wg=Number.parseInt(r,10),2===A.length&&(t=A[1].trim()));break;case "position":A=
D.split(",");w=A[0];l.Cf=Number.parseInt(w,10);2===A.length&&(x=A[1].trim());break;case "align":switch(D){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.Wg=100,t||(t="end"));if(!w)switch(l.textAlign){case 0:l.Cf=0;break;case 1:l.Cf=100;break;default:l.Cf=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.lg=0>r||8<r?7:r;f=f.substring(f4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=kDa(m,n,5,x),n=new p3(m,n,5,h.id,l,!1,g.Vb(f)?void 0:f),c.push(h),c.push(n),h.o.push(n);else for(t=l.split(vDa),1===t.length?(l=5,x=kDa(m,n,l,x)):(r=l=6,x=Object.assign({Ti:32},x),x=new q3(m,n,r,"_"+r3++,x)),c.push(x),r=m,w=0;w<t.length;w++)p=t[w],0===w%2?(A=g.Y0("<html>"+p+"</html>"),A.getElementsByTagName("parsererror").length?
(D=A.createElement("span"),D.appendChild(A.createTextNode(p))):D=A.firstChild,jDa(this,r,n-(r-m),l,x,0<w,D,f,c)):r=T3(p)+h}f4.lastIndex=0}}return c};
var uDa=/^NOTE/,tDa=/(?:\r\n|\r|\n){2,}/,f4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),vDa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.u(U3,g.B);U3.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
U3.prototype.reset=function(){this.o&&this.o.reset()};
U3.prototype.V=function(){g.B.prototype.V.call(this);this.clear()};var e4={windowColor:"#080808",windowOpacity:0,textAlign:2,lg:7,Cf:50,Wg:100,ac:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(X3,g.FS);g.k=X3.prototype;g.k.V=function(){if(this.C||this.P){var a=this.G.app.C;a&&!a.ea()&&a.xn()}else qDa(this,!1);g.FS.prototype.V.call(this)};
g.k.load=function(){var a=this;g.FS.prototype.load.call(this);var b=!g.Q(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.H=this.player.getAudioTrack();if(this.u)this.o&&(this.na.clear(),this.C?nDa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Gr(this.o,"json3",function(d,e,f,h){if(d){a.u.gE()&&(a.S=[],g.hX(a.G,"captions"),a.U.kb(),a.na.reset());var l=a.na;f=f||0;h=h||0;if(l.u.Z("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.Qt(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),R3(d)||(d=g.Te(new Uint8Array(d))))}}else"string"===typeof d||R3(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.Qt(m,0,1835295092))&&m.size?g.Te(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!R3(n))throw Error("Invalid binary caption track data");l.o||(l.o=new Q3(r,e));var t=l.o.A(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.o||(l.o=new S3),p=l.o.A(e,r),.01>Math.random()&&g.Dr(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.o||(l.o=new z3(mDa(e)));n=l.o.A(p,f);break b}catch(H){g.Cr(H);n=[];break b}r=g.Y0(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.o||(l.o=new t3(mDa(e),l.u));n=l.o.A(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var A=Error("Unsupported subtitles format in web player (Format1)");A.params=p;throw A;}var D=Error("Invalid caption track data");D.params=p;throw D;}t=n}var E=t}catch(H){g.Cr(H),l.clear(),E=[]}else E=[];g.nM(a.player,E);!a.W||a.P||b4(a)||g.kC(a.A)||g.lC(a.A)||(a.aa.sg(),E=NCa({lg:0,Cf:5,Wg:5,u:2,textAlign:0,o:0,lang:"de"}),a.ca=[E],l=["Klicke auf ",", um die Einstellungen aufzurufen."],a.ra||(t=new g.CM(g.mN()),g.C(a,t),a.ra=t.element),
t=E.end-E.start,(e=g.GE(a.o))&&a.ca.push(new p3(E.start,t,0,E.id,e)),a.ca.push(new p3(E.start,t,0,E.id,l[0]),new p3(E.start,t,0,E.id,a.ra,!0),new p3(E.start,t,0,E.id,l[1],!0)),g.nM(a.player,a.ca),a.aa.kb());!a.W||a.P||b4(a)||(c4(a,"module-enabled",!0),a.H&&(a.H.C=a.o),(E=g.Z(a.player.app))&&g.bU(E.H));a.W=!1}}),!b||this.C||this.P||b4(this)||this.player.la("captionschanged",d3(this.o))),b||(this.o&&!b4(this)?this.player.la("captionschanged",d3(this.o)):this.player.la("onCaptionsTrackListChanged"));
else{var c;this.xa?c=new k3(this.videoData.ga,this.player):this.Ja?c=new h3(this.A,this.videoData,this.player.getAudioTrack()):c=new l3(this.videoData.un,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.A.captionsLanguagePreference||g.IF(this.videoData,"yt:cc_default_lang")||this.A.kf,this.videoData.zu,this.A);this.u=c;g.C(this,this.u);c.Hr(function(){var d;a.W||Y3(a)?d=a4(a,a.W):Z3(a)&&(d=$3(a));if(a.C||a.P){for(var e=a.u.vk(!0),f=[],h=0;h<e.length;h++){var l=e[h],m=g.Ce("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.GE(l));m.setAttribute("srclang",e3(l));m.setAttribute("id",l.toString());a.P||m.setAttribute("src",a.u.dm(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.G.app.C;d.on(f);f=d.Ea();a.Ca&&a.X.K(f.textTracks,"change",a.nO)}else!a.o&&d&&d4(a,d),a.player.la("onCaptionsTrackListChanged"),a.player.la("onApiChange")})}};
g.k.unload=function(){this.C&&this.o?nDa(this,!1):(this.aa&&this.aa.sg(),g.hX(this.player,"captions"),this.S=[],this.u&&this.u.Ki(),this.na.clear(),this.J&&g.nM(this.player,this.J),this.my());g.FS.prototype.unload.call(this);var a=g.Z(this.player.app);a&&g.bU(a.H);this.player.la("captionschanged",{})};
g.k.create=function(){(this.oa?this.C||this.P:Z3(this)||Y3(this))&&this.load()};
g.k.nO=function(){for(var a=this.G.app.C.Ea().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=this.u.vk(!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.o:null)!==b&&d4(this,b,!0)};
g.k.YP=function(){!this.o&&this.C||this.unload()};
g.k.PJ=function(a){this.S.push(a);this.U.kb()};
g.k.QJ=function(a){g.qb(this.S,a);this.u instanceof k3&&this.u.C&&g.oM(this.player.app,[a],void 0);this.U.kb()};
g.k.dP=function(a){if(a instanceof q3){var b=this.M[a.id];b&&b.u!==a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=oDa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.fa[b]||(this.fa[b]=[]),this.fa[b].push(a)};
g.k.kP=function(){pDa(this,this.ca);this.ca=null};
g.k.uF=function(){var a=this;this.U.stop();g.Wb(this.fa);this.S.sort(g.DD);var b=this.S;if(this.J){var c=g.Ie(b,function(d){return-1===this.J.indexOf(d)},this);
c.length&&(b=c)}g.Gb(b,this.dP,this);g.Ib(this.M,function(d,e){a.fa[e]?(d.element.parentNode||(d instanceof o3||d instanceof n3||g.Lb(a.M,function(f,h){h!==e&&f.u.params.lg===d.u.params.lg&&f.u.params.Cf===d.u.params.Cf&&f.u.params.Wg===d.u.params.Wg&&(f.dispose(),delete a.M[h]);return h===e},a),g.OO(a.player,d.element,4)),d.rl(a.fa[e])):(d.dispose(),delete a.M[e])},this)};
g.k.oP=function(){V3(this,{},!0);g.Q(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.la("captionssettingschanged")};
g.k.OH=function(){var a=e4.ac;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Bg?3:a.bold?1:a.Bg?2:0,textOpacity:a.textOpacity,windowColor:e4.windowColor,windowOpacity:e4.windowOpacity};var b=W3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.CF=function(a,b){var c={};g.Va(c,W3(this,"display-settings"));g.Va(c,a);V3(this,c,b);this.player.la("captionssettingschanged")};
g.k.my=function(){!this.C&&this.loaded&&(g.Ib(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.uF())};
g.k.Hd=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Zd(b,-2,4);this.CF({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&d4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.A.A&&c4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Ra(b))break;if(g.Vb(b)){d4(this,null,!0);break}for(var d=this.u.vk(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
uCa(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||d4(this,c,!0)}else return this.loaded&&this.o&&!b4(this)?d3(this.o):{};return"";case "tracklist":return this.u?g.Oc(this.u.vk(!(!b||!b.includeAsr)),function(h){return d3(h)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.C||void 0===b||qDa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.A&&a.push("stickyLoading");return a};
g.k.RI=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.k.PP=function(){this.loaded&&this.o&&!b4(this)?(c4(this,"module-enabled",!1),this.unload(),Z3(this,!0)&&d4(this,$3(this),!1)):d4(this,b4(this)||!this.o?a4(this,!0):this.o,!0)};
g.k.CL=function(){var a=b4(this);Z3(this,a)?d4(this,this.player.getAudioTrack().u,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.oa?this.C||this.P:Z3(this)||Y3(this))&&(a?d4(this,a4(this),!1):this.load()))};g.vX.captions=X3;})(_yt_player);
