(function(g){var window=this;var fEa=function(a,b){a.la("onAutonavCoundownStarted",b)},O4=function(a,b,c){var d=b.Ba();
g.J(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.nd(c?c:"mqdefault.jpg");var f=b instanceof g.bF&&b.lengthSeconds?g.jO(b.lengthSeconds):null,h=!!e;e=h&&"RD"===(new g.tG(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.bF?b.isLivePlayback:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.pn||g.dJ("$TITLE ansehen",{TITLE:b.title}),duration:f,url:b.fj(),is_live:l,is_list:h,is_mix:e,background:c?
"background-image: url("+c+")":""};b instanceof g.uG&&(d.playlist_length=b.getLength());a.update(d)},P4=function(a){var b=a.N();
g.V.call(this,{D:"a",O:{href:"{{url}}",target:b.u?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{D:"div",I:"ytp-autonav-endscreen-upnext-thumbnail",O:{style:"{{background}}"},L:[{D:"div",da:["ytp-autonav-duration-card"],T:"{{duration}}"}]},{D:"div",da:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],T:"{{title}}"},{D:"div",da:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-view-card"],T:"{{author_and_views}}"}]});
this.G=a;this.suggestion=null},Q4=function(a){var b=a.N(),c=b.u;
g.V.call(this,{D:"div"});this.G=a;this.B=this.suggestion=null;this.o=new g.V({D:"a",O:{href:"{{url}}",target:c?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{D:"div",T:"N\u00e4chstes Video",I:"ytp-autonav-endscreen-upnext-header"},{D:"div",I:"ytp-autonav-endscreen-upnext-thumbnail",O:{style:"{{background}}"}},{D:"div",I:"ytp-autonav-endscreen-upnext-title",T:"{{title}}"},{D:"div",I:"ytp-autonav-endscreen-upnext-author",
T:"{{author}}"}]});g.C(this,this.o);this.o.Y(this.element);this.u=new g.V({D:"div"});g.C(this,this.u);this.u.Y(this.element);this.cancelButton=new g.V({D:"span",da:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],O:{"aria-label":"Autoplay abbrechen"},T:"Abbrechen"});g.C(this,this.cancelButton);this.cancelButton.Y(this.u.element);this.cancelButton.ia("click",this.C,this);this.playButton=new g.V({D:"a",da:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],
O:{href:"{{url}}","aria-label":"N\u00e4chstes Video starten"},T:"Play Now"});g.C(this,this.playButton);this.playButton.Y(this.u.element);this.playButton.ia("click",this.F,this)},R4=function(a,b){g.V.call(this,{D:"div",
da:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},S4=function(a){R4.call(this,a,"autonav-endscreen");
this.videoData=this.suggestions=null;this.table=new g.V({D:"div",L:[{D:"div",I:"ytp-autonav-endscreen-upnext-header",T:"Weitere Videos"}]});this.C=new g.V({D:"div",I:"ytp-suggestions-container"});this.videos=[];this.u=null;this.B=!1;this.A=new Q4(this.player);g.C(this,this.A);this.o=new g.qR(this);g.C(this,this.o);this.A.Y(this.element);g.C(this,this.table);this.table.Y(this.element);g.C(this,this.C);this.C.Y(this.table.element);this.hide()},gEa=function(a,b){return g.Oc(b.suggestions,function(c){c=
g.uZ(a.player.N(),c);
g.C(a,c);return c})},U4=function(a){g.V.call(this,{D:"div",
da:["ytp-upnext","ytp-player-content"],O:{"aria-label":"{{aria_label}}"},L:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",O:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",L:[{D:"span",I:"ytp-upnext-header",T:"N\u00e4chstes Video"},{D:"span",I:"ytp-upnext-title",T:"{{title}}"},{D:"span",I:"ytp-upnext-author",T:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",O:{role:"button",href:"{{url}}","aria-label":"N\u00e4chstes Video starten"},L:[{D:"svg",O:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},L:[{D:"circle",I:"ytp-svg-autoplay-circle",O:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",O:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",O:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",L:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",
T:"Autoplay ist pausiert"}]}]});this.api=a;this.cancelButton=null;this.C=this.ba("ytp-svg-autoplay-ring");this.u=this.notification=this.o=this.suggestion=null;this.A=new g.G(this.xq,5E3,this);this.B=0;var b=this.ba("ytp-upnext-cancel");this.cancelButton=new g.V({D:"button",da:["ytp-upnext-cancel-button","ytp-button"],O:{tabindex:"0","aria-label":"Autoplay abbrechen"},T:"Abbrechen"});g.C(this,this.cancelButton);this.cancelButton.ia("click",this.xK,this);this.cancelButton.Y(b);g.C(this,this.A);g.kX(this.api,
this.element,this,18788);b=this.ba("ytp-upnext-autoplay-icon");this.K(b,"click",this.yK);this.VC();this.K(a,"autonavvisibility",this.VC);this.K(a,"mdxnowautoplaying",this.FM);this.K(a,"mdxautoplaycanceled",this.GM);this.K(a,"mdxautoplayupnext",this.AF);T4(this)&&(a=(a=g.WW(g.SW(this.api)))?a.MH():null)&&this.AF(a);g.J(this.element,"ytp-upnext-mobile",this.api.N().o)},W4=function(a,b){a.o||(g.No("a11y-announce","N\u00e4chstes Video "+a.suggestion.title),a.B=(0,g.M)(),a.o=new g.G(function(){V4(a,b)},
25),V4(a,b),fEa(a.api,b||g.O(a.api.N().experiments,"autoplay_time")||1E4));
g.yn(a.element,"ytp-upnext-autoplay-paused")},T4=function(a){return 3===a.api.getPresentingPlayerType()},V4=function(a,b){var c=b||g.O(a.api.N().experiments,"autoplay_time")||1E4,d=Math.min(hEa(a),c);
c=Math.min(d/c,1);a.C.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&!T4(a)?a.select(!0):a.o&&a.o.start()},hEa=function(a){return(0,g.M)()-a.B},Y4=function(a){X4(a);
a.B=(0,g.M)();V4(a);g.I(a.element,"ytp-upnext-autoplay-paused")},X4=function(a){a.o&&(a.o.dispose(),a.o=null)},iEa=function(a){R4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.o=new g.V({D:"div",I:"ytp-subscribe-card",L:[{D:"img",I:"ytp-author-image",O:{src:b.se}},{D:"div",I:"ytp-subscribe-card-right",L:[{D:"div",I:"ytp-author-name",T:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.C(this,this.o);this.o.Y(this.element);this.subscribeButton=new g.lY("Abonnieren",null,"Abo beenden",null,!0,!1,b.eg,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.subscribeButton);this.subscribeButton.Y(this.o.ba("html5-subscribe-button-container"));
this.hide()},Z4=function(a){var b=a.N(),c=g.nB||g.ng?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",da:e,O:{href:"{{url}}",target:d?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{D:"div",I:"ytp-videowall-still-image",O:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",L:[{D:"span",I:"ytp-videowall-still-info-bg",L:[{D:"span",I:"ytp-videowall-still-info-content",O:c,L:[{D:"span",I:"ytp-videowall-still-info-title",T:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
T:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",T:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",T:"{{duration}}"}]}]}]},{D:"span",da:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",L:[" (",{D:"span",T:"{{playlist_length}}"},")"]}]},{D:"span",da:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],L:[{D:"span",
I:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",T:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.o=new g.ns(this);g.C(this,this.o);this.ia("click",this.onClick);this.ia("keypress",this.A);this.o.K(a,"videodatachange",this.Ha);g.JM(a,this.element,this);this.Ha()},$4=function(a){R4.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.M=!1;this.H=null;this.u=new g.qR(this);g.C(this,this.u);this.F=new g.G(function(){g.I(b.element,"ytp-show-tiles")},0);
g.C(this,this.F);var c=new g.V({D:"button",da:["ytp-button","ytp-endscreen-previous"],O:{"aria-label":"Vorheriges"},L:[g.UM()]});g.C(this,c);c.Y(this.element);c.ia("click",this.yJ,this);this.table=new g.CM({D:"div",I:"ytp-endscreen-content"});g.C(this,this.table);this.table.Y(this.element);c=new g.V({D:"button",da:["ytp-button","ytp-endscreen-next"],O:{"aria-label":"Weiter"},L:[g.VM()]});g.C(this,c);c.Y(this.element);c.ia("click",this.xJ,this);this.o=new U4(a);g.C(this,this.o);g.OO(this.player,this.o.element,
4);this.hide()},a5=function(a){return g.jX(a.player)&&a.gq()&&!a.B},jEa=function(a,b){return g.Oc(b.suggestions,function(c){c=g.uZ(a.G.N(),c);
g.C(a,c);return c})},b5=function(a){var b=a.tw();
b!==a.M&&(a.M=b,a.player.R("autonavvisibility"))},c5=function(a){g.FS.call(this,a);
this.endScreen=null;this.listeners=new g.ns(this);g.C(this,this.listeners);this.o=a.N();kEa(a)?this.o.Z("web_new_autonav_endscreen")?this.endScreen=new S4(a):this.endScreen=new $4(this.player):this.o.Cc?this.endScreen=new iEa(this.player):this.endScreen=new R4(this.player);g.C(this,this.endScreen);g.OO(this.player,this.endScreen.element,4);this.JE();this.listeners.K(a,"videodatachange",this.JE,this);this.listeners.K(a,g.ED("endscreen"),this.uJ,this);this.listeners.K(a,g.FD("endscreen"),this.vJ,this)},
kEa=function(a){a=a.N();
return a.Ra&&!a.Cc};g.u(P4,g.V);P4.prototype.Cd=function(a,b,c){c&&g.F(this.element,{marginLeft:Math.floor(14*a)+"px"});c=this.element.children[0];g.F(c,{width:Math.floor(220*a)+"px",height:Math.floor(118*b)+"px"});(c=c.children[0])&&g.F(c,{margin:Math.floor(4*b)+"px "+Math.floor(4*a)+"px"});for(c=0;c<Math.min(this.element.children.length,lEa.length);++c)g.F(this.element.children[c],{marginTop:Math.floor(lEa[c]*b)+"px",width:Math.floor(220*a)+"px"})};
var lEa=[20,13,11];g.u(Q4,g.V);
Q4.prototype.Cd=function(a,b){g.F(this.element,{marginTop:Math.floor(47*b)+"px",width:Math.floor(360*a)+"px"});g.Ag(this.o.element.children[1],Math.floor(360*a),Math.floor(202*b));var c=Math.floor(175*a),d=Math.floor(36*b);g.Ag(this.cancelButton.element,c,d);g.Ag(this.playButton.element,c,d);c={marginTop:Math.floor(20*b)+"px"};for(d=1;d<this.o.element.childElementCount;d++)g.F(this.o.element.children[d],c);g.F(this.u.element,c);this.A&&g.F(this.o.element.children[3],{marginTop:Math.floor(12*b)+"px"})};
Q4.prototype.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a)};
Q4.prototype.F=function(a){g.FX(a,this.G)&&this.select()};
Q4.prototype.C=function(){g.VW(this.G,!0)};g.u(R4,g.V);g.k=R4.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.gq=function(){return!1};
g.k.tw=function(){return!1};
g.k.vB=function(){return!1};g.u(S4,R4);g.k=S4.prototype;g.k.create=function(){R4.prototype.create.call(this);this.o.K(this.player,"appresize",this.Cd);this.o.K(this.player,"onVideoAreaChange",this.Cd);this.o.K(this.player,"videodatachange",this.Ha);this.o.K(this.player,"autonavchange",this.fC);this.o.K(this.player,"autonavcancel",this.tJ);this.Ha();this.Cd()};
g.k.show=function(){R4.prototype.show.call(this);(this.B||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.VW(this.player,!1)};
g.k.Cd=function(){var a=this.player.xk(!0,this.player.isFullscreen()),b=a.width/1024;a=a.height/576;var c=g.jX(this.player)&&this.gq()&&!this.u,d=this.A;d.B=c;d.B?d.u.show():d.u.hide();this.A.Cd(b,a);if(c)g.F(this.element,{paddingLeft:Math.floor(320*b)+"px"}),this.table.hide();else{g.F(this.element,{padding:"0 "+Math.floor(75*b)+"px"});g.F(this.table.element,{marginTop:Math.floor(47*a)+"px",width:Math.floor(454*b)+"px"});c=g.q(this.videos.entries());for(d=c.next();!d.done;d=c.next()){d=g.q(d.value);
var e=d.next().value;d.next().value.Cd(b,a,1===e%2)}this.table.show()}};
g.k.Ha=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=gEa(this,a))&&this.suggestions.length){a=this.A;var b=this.suggestions[0];a.suggestion!==b&&(a.suggestion=b,O4(a.o,b),a.suggestion.it?(a.A||(a.A=new g.V({D:"div",L:[{D:"svg",O:{fill:"none",height:"16",width:"74"},L:[{D:"path",O:{d:"M22.26 8.83V12h-1.49V3.47h3.27c.95 0 1.7.25 2.26.74.57.5.85 1.16.85 1.97 0 .84-.28 1.49-.83 1.95-.55.47-1.31.7-2.3.7h-1.76zm0-1.19h1.78c.52 0 .93-.12 1.2-.37.28-.25.42-.6.42-1.08 0-.46-.14-.82-.42-1.1a1.62 1.62 0 00-1.16-.43h-1.82v2.98zm9.37-.68a3.52 3.52 0 00-.58-.05c-.65 0-1.1.25-1.32.75V12h-1.42V5.66h1.36l.03.7a1.6 1.6 0 011.43-.82c.2 0 .37.03.5.08v1.34zm3.57 5.16c-.9 0-1.63-.29-2.2-.85a3.1 3.1 0 01-.83-2.28v-.17c0-.63.12-1.2.36-1.7a2.72 2.72 0 012.5-1.58c.87 0 1.54.28 2 .83.48.55.72 1.33.72 2.34v.57H33.6c.05.52.22.94.53 1.24.3.3.7.46 1.16.46.65 0 1.18-.26 1.59-.79l.77.73c-.26.38-.6.68-1.02.89-.42.2-.9.3-1.43.3zm-.17-5.43c-.39 0-.7.13-.94.4-.24.28-.4.66-.46 1.15h2.71v-.1a1.72 1.72 0 00-.38-1.09 1.18 1.18 0 00-.93-.36zm5.17-1.03l.04.66a2.28 2.28 0 011.83-.78c.84 0 1.42.33 1.74.98.46-.65 1.1-.98 1.94-.98.7 0 1.22.2 1.56.58.34.39.52.96.53 1.71V12H46.4V7.87c0-.4-.08-.7-.26-.88-.18-.19-.47-.28-.87-.28-.33 0-.6.09-.8.26-.2.17-.35.4-.43.68V12h-1.42V7.83c-.02-.75-.4-1.12-1.14-1.12-.57 0-.97.23-1.21.7V12h-1.43V5.66h1.35zM50.8 12H49.4V5.66h1.42V12zm-1.5-7.99c0-.22.06-.4.2-.54.14-.15.34-.22.6-.22.25 0 .45.07.6.22.13.14.2.32.2.54 0 .22-.07.4-.2.54-.15.14-.35.21-.6.21-.26 0-.46-.07-.6-.2a.75.75 0 01-.2-.55zm6.9 7.37a2.2 2.2 0 01-1.78.74c-.69 0-1.21-.2-1.57-.6-.35-.4-.52-1-.52-1.75V5.66h1.42v4.09c0 .8.34 1.2 1 1.2.7 0 1.16-.24 1.4-.74V5.66h1.43V12h-1.34l-.04-.62zm4.17-5.72l.04.66a2.28 2.28 0 011.83-.78c.84 0 1.42.33 1.74.98.46-.65 1.1-.98 1.94-.98.7 0 1.22.2 1.56.58.34.39.52.96.53 1.71V12h-1.43V7.87c0-.4-.08-.7-.26-.88-.18-.19-.47-.28-.87-.28-.33 0-.6.09-.8.26-.2.17-.35.4-.43.68V12h-1.42V7.83c-.02-.75-.4-1.12-1.14-1.12-.57 0-.97.23-1.21.7V12h-1.43V5.66h1.35z",
fill:"#aaa"}},{D:"rect",O:{fill:"#d00",height:"13.96",rx:"1",width:"13.96",x:"1.96",y:"1"}},{D:"path",O:{"clip-rule":"evenodd",d:"M7.7 12.5v-3h1.53c1.01 0 1.8-.24 2.37-.72.57-.48.86-1.14.86-1.97 0-.55-.13-1.04-.4-1.47a2.58 2.58 0 00-1.11-1 3.84 3.84 0 00-1.69-.35H5.94v8.5H7.7zm1.56-4.42H7.7V5.4h1.6c.44 0 .78.14 1.02.4.25.25.37.59.37 1 0 .41-.12.72-.37.94-.24.22-.6.33-1.06.33z",fill:"#fff","fill-rule":"evenodd"}}]}]}),a.A.Y(a.o.element,2),g.C(a,a.A)),a.A.show()):a.A&&a.A.hide());for(a=0;a<mEa.length;++a){var c=
mEa[a];this.suggestions&&this.suggestions[c]&&(this.videos[a]=new P4(this.player),b=this.videos[a],c=this.suggestions[c],b.suggestion!==c&&(b.suggestion=c,O4(b,c)),g.C(this,this.videos[a]),this.videos[a].Y(this.C.element))}}this.Cd()}};
g.k.fC=function(a){1===a?(this.B=!1,this.u=this.videoData.clientPlaybackNonce,this.Pa&&this.Cd()):this.B=!0};
g.k.tJ=function(a){a?this.fC(1):(this.u=null,this.B=!1)};
g.k.gq=function(){return 1!==this.videoData.autonavState};
var mEa=[1,3,2,4];g.u(U4,g.V);g.k=U4.prototype;g.k.xq=function(){this.notification&&(this.A.stop(),this.sb(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.VC=function(){g.FM(this,g.TW(this.api));g.NM(this.api,this.element,g.TW(this.api))};
g.k.aN=function(){window.focus();this.xq()};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.Q(this.api.N().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ba(),this.xq(),this.notification=new Notification("N\u00e4chstes Video",{body:b.title,icon:b.nd()}),this.u=this.K(this.notification,"click",this.aN),this.A.start())}X4(this);this.api.nextVideo(!1,a)};
g.k.yK=function(a){!g.Ke(this.cancelButton.element,g.cp(a))&&g.FX(a,this.api)&&this.select()};
g.k.xK=function(){g.VW(this.api,!0)};
g.k.FM=function(a){T4(this);this.show();W4(this,a)};
g.k.AF=function(a){T4(this);this.suggestion&&this.suggestion.Ba().videoId===a.Ba().videoId||(this.suggestion=a,O4(this,a,"hqdefault.jpg"))};
g.k.GM=function(){T4(this);X4(this);this.hide()};
g.k.V=function(){X4(this);this.xq();g.V.prototype.V.call(this)};g.u(iEa,R4);g.u(Z4,g.V);Z4.prototype.select=function(){var a=this.suggestion.Ba().videoId,b=this.suggestion.getPlaylistId();(g.Q0(this.api.app,a,this.suggestion.Yc,b,void 0,this.suggestion.hA||void 0)||this.api.Z("web_player_endscreen_double_log_fix_killswitch"))&&g.lX(this.api,this.element)};
Z4.prototype.onClick=function(a){g.FX(a,this.api,this.u,this.suggestion.Yc||void 0)&&this.select()};
Z4.prototype.A=function(a){switch(a.keyCode){case 13:case 32:g.hp(a)||(this.select(),g.gp(a))}};
Z4.prototype.Ha=function(){var a=this.api.getVideoData(),b=this.api.N();this.u=a.Dc?!1:b.u};g.u($4,R4);g.k=$4.prototype;g.k.create=function(){R4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=jEa(this,a),this.videoData=a);this.Cd();this.u.K(this.player,"appresize",this.Cd);this.u.K(this.player,"onVideoAreaChange",this.Cd);this.u.K(this.player,"videodatachange",this.Ha);this.u.K(this.player,"autonavchange",this.uw);this.u.K(this.player,"autonavcancel",this.wJ);a=this.videoData.autonavState;a!==this.H&&this.uw(a);this.u.K(this.element,"transitionend",this.oO)};
g.k.destroy=function(){g.ts(this.u);g.bg(this.stills);this.stills=[];this.suggestions=null;R4.prototype.destroy.call(this);g.yn(this.element,"ytp-show-tiles");this.F.stop();this.H=this.videoData.autonavState};
g.k.gq=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){R4.prototype.show.call(this);g.yn(this.element,"ytp-show-tiles");this.player.N().o?g.qn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.VW(this.player,!1);a5(this)?(b5(this),2===this.videoData.autonavState?this.player.N().Z("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.o.select(!0):W4(this.o):3===this.videoData.autonavState&&Y4(this.o)):(g.VW(this.player,!0),b5(this))};
g.k.hide=function(){R4.prototype.hide.call(this);Y4(this.o);b5(this)};
g.k.oO=function(a){g.cp(a)===this.element&&this.Cd()};
g.k.Cd=function(){if(this.suggestions&&this.suggestions.length){g.I(this.element,"ytp-endscreen-paginate");var a=this.G.xk(!0,this.G.isFullscreen()),b=g.OW(this.G);b&&(b=b.od()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Ag(a,m,n);g.F(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.o;f=this.suggestions[0];c.suggestion=f;O4(c,f,"hqdefault.jpg");g.J(this.element,"ytp-endscreen-takeover",a5(this));b5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=
e-2?r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.$d(p+this.A,l),0!==r){t=this.stills[c];t||(t=new Z4(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var x=Math.floor(m*f/b),A=Math.floor(n*(h+r)/e)-w-4,D=Math.floor(m*(f+r)/b)-x-4;g.sg(t.element,x,w);g.Ag(t.element,D,A);g.F(t.element,"transitionDelay",(h+f)/20+"s");g.J(t.element,"ytp-videowall-still-mini",1===r);g.J(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.N(),w=g.wn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",O4(r,p,w),g.WB(t)&&(t=p.fj(),t=g.Jd(t,g.UT({},"emb_rel_end")),r.ka("url",t)),(p=(p=p.Yc)&&p.itct)&&g.KM(r.api,r.element,p));c++}g.J(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.He(e.element),g.ag(e);this.stills.length=c}};
g.k.Ha=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=jEa(this,a),this.videoData=a,this.Cd())};
g.k.xJ=function(){this.A+=this.stills.length;this.Cd()};
g.k.yJ=function(){this.A-=this.stills.length;this.Cd()};
g.k.vB=function(){return!!this.o.o};
g.k.uw=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,X4(this.o),this.Pa&&this.Cd()):(this.C=!0,this.Pa&&a5(this)&&(2===a?W4(this.o):3===a&&Y4(this.o)))};
g.k.wJ=function(a){if(a){for(a=0;a<this.stills.length;a++)g.NM(this.G,this.stills[a].element,!0);this.uw(1)}else this.B=null,this.C=!1;this.Cd()};
g.k.tw=function(){return this.Pa&&a5(this)};g.u(c5,g.FS);g.k=c5.prototype;g.k.VB=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!kEa(this.player)||b;var c=a.Dl||g.eC(a.Fa),d=g.R0(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.UB=function(){return this.endScreen.tw()};
g.k.zI=function(){return this.UB()?this.endScreen.vB():!1};
g.k.V=function(){g.hX(this.player,"endscreen");g.FS.prototype.V.call(this)};
g.k.load=function(){g.FS.prototype.load.call(this);this.endScreen.show()};
g.k.unload=function(){g.FS.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.uJ=function(a){this.VB()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.vJ=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.JE=function(){g.hX(this.player,"endscreen");var a=this.player.getVideoData();a=new g.BD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.BD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.nM(this.player,[a,b])};g.vX.endscreen=c5;})(_yt_player);
